import type { LeaderSeed } from '../../src/data/types';
import { leanings } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_heads_of_state_of_Argentina`;

const countryId = 20;

export const argentina: LeaderSeed[] = [
	{
		id: 1000,
		countryId,
		name: `Viceroyalty of the Río de la Plata - United Provinces of the Rio de la Plata`,
		party: `Kingdom of Spain`,
		leaning: leanings.MONARCHY,
		tookOffice: `1 August 1776`,
		leftOffice: `25 May 1810`,
	},
	{
		id: 1001,
		countryId,
		name: `Cornelio Saavedra - United Provinces of the Rio de la Plata`,
		party: `Junta President - United Provinces of the Rio de la Plata`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 May 1810`,
		leftOffice: `26 August 1811`,
	},
	{
		id: 1002,
		countryId,
		name: `Domingo Matheu - United Provinces of the Rio de la Plata`,
		party: `Junta President - United Provinces of the Rio de la Plata`,
		leaning: leanings.CENTRIST,
		tookOffice: `26 August 1811`,
		leftOffice: `23 September 1811`,
	},
	{
		id: 1003,
		countryId,
		name: `First Triumvirate - Feliciano Chiclana, Manuel de Sarratea, Juan José Paso, Juan Martín de Pueyrredón - United Provinces of the Rio de la Plata`,
		party: `First Triumvirate - United Provinces of the Rio de la Plata`,
		leaning: leanings.CENTRIST,
		tookOffice: `23 September 1811`,
		leftOffice: `8 October 1812`,
	},
	{
		id: 1004,
		countryId,
		name: `Second Triumvirate - Nicolás Rodríguez Peña, Antonio Álvarez Jonte, Juan José Paso, Gervasio Antonio de Posadas, Juan Larrea - United Provinces of the Rio de la Plata`,
		party: `Second Triumvirate`,
		leaning: leanings.CENTRIST,
		tookOffice: `8 October 1812`,
		leftOffice: `31 January 1814`,
	},
	{
		id: 1005,
		countryId,
		name: `Gervasio Antonio de Posadas - United Provinces of the Rio de la Plata`,
		party: `Supreme Director`,
		leaning: leanings.CENTRIST,
		tookOffice: `31 January 1814`,
		leftOffice: `9 January 1815`,
	},
	{
		id: 1006,
		countryId,
		name: `Carlos María de Alvear - United Provinces of the Rio de la Plata`,
		party: `Supreme Director`,
		leaning: leanings.CENTRIST,
		tookOffice: `9 January 1815`,
		leftOffice: `18 April 1815`,
	},
	{
		id: 1007,
		countryId,
		name: `Junta of Observation - José de San Martín, Matías de Irigoyen, Manuel de Sarratea - United Provinces of the Rio de la Plata`,
		party: `Supreme Director`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 April 1815`,
		leftOffice: `20 April 1815`,
	},
	{
		id: 1008,
		countryId,
		name: `José Rondeau - United Provinces of the Rio de la Plata`,
		party: `Supreme Director`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 April 1815`,
		leftOffice: `21 April 1815`,
	},
	{
		id: 1009,
		countryId,
		name: `Ignacio Álvarez Thomas - United Provinces of the Rio de la Plata`,
		party: `Supreme Director`,
		leaning: leanings.CENTRIST,
		tookOffice: `21 April 1815`,
		leftOffice: `16 April 1816`,
	},
	{
		id: 1010,
		countryId,
		name: `Antonio González de Balcarce - United Provinces of the Rio de la Plata`,
		party: `Supreme Director`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 April 1816`,
		leftOffice: `9 July 1816`,
	},
	{
		id: 1011,
		countryId,
		name: `Juan Martín de Pueyrredón - United Provinces of the Rio de la Plata`,
		party: `Supreme Director`,
		leaning: leanings.CENTRIST,
		tookOffice: `9 July 1816`,
		leftOffice: `9 June 1819`,
	},
	{
		id: 1012,
		countryId,
		name: `José Rondeau - United Provinces of the Rio de la Plata`,
		party: `Supreme Director`,
		leaning: leanings.CENTRIST,
		tookOffice: `9 June 1819`,
		leftOffice: `1 February 1820`,
	},
	{
		id: 1013,
		countryId,
		name: `Juan Pedro Aguirre - United Provinces of the Rio de la Plata`,
		party: `Supreme Director`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 February 1820`,
		leftOffice: `11 February 1820`,
	},
	{
		id: 1014,
		countryId,
		name: `Matías de Irigoyen - United Provinces of the Rio de la Plata`,
		party: `Governor of Buenos Aires`,
		leaning: leanings.CENTRIST,
		tookOffice: `11 February 1820`,
		leftOffice: `18 February 1820`,
	},
	{
		id: 1015,
		countryId,
		name: `Manuel de Sarratea - United Provinces of the Rio de la Plata`,
		party: `Governor of Buenos Aires`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 February 1820`,
		leftOffice: `6 March 1820`,
	},
	{
		id: 1016,
		countryId,
		name: `Juan Ramón Balcarce - United Provinces of the Rio de la Plata`,
		party: `Governor of Buenos Aires`,
		leaning: leanings.CENTRIST,
		tookOffice: `6 March 1820`,
		leftOffice: `11 March 1820`,
	},
	{
		id: 1017,
		countryId,
		name: `Manuel de Sarratea - United Provinces of the Rio de la Plata`,
		party: `Governor of Buenos Aires`,
		leaning: leanings.CENTRIST,
		tookOffice: `11 March 1820`,
		leftOffice: `2 May 1820`,
	},
	{
		id: 1018,
		countryId,
		name: `Ildefonso Ramos Mexía - United Provinces of the Rio de la Plata`,
		party: `Governor of Buenos Aires`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 May 1820`,
		leftOffice: `20 June 1820`,
	},
	{
		id: 1019,
		countryId,
		name: `Ildefonso Ramos Mexía and Miguel Estanislao Soler - United Provinces of the Rio de la Plata`,
		party: `Governor of Buenos Aires`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 June 1820`,
		leftOffice: `23 June 1820`,
	},
	{
		id: 1020,
		countryId,
		name: `Miguel Estanislao Soler - United Provinces of the Rio de la Plata`,
		party: `Governor of Buenos Aires`,
		leaning: leanings.CENTRIST,
		tookOffice: `23 June 1820`,
		leftOffice: `29 June 1820`,
	},
	{
		id: 1021,
		countryId,
		name: `Manuel Dorrego - United Provinces of the Rio de la Plata`,
		party: `Governor of Buenos Aires`,
		leaning: leanings.CENTRIST,
		tookOffice: `29 June 1820`,
		leftOffice: `20 September 1820`,
	},
	{
		id: 1022,
		countryId,
		name: `Martín Rodríguez - United Provinces of the Rio de la Plata`,
		party: `Governor of Buenos Aires`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 September 1820`,
		leftOffice: `2 April 1824`,
	},
	{
		id: 1023,
		countryId,
		name: `Juan Gregorio de las Heras - United Provinces of the Rio de la Plata`,
		party: `Governor of Buenos Aires`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 April 1824`,
		leftOffice: `8 February 1826`,
	},
	{
		id: 1024,
		countryId,
		name: `Bernardino Rivadavia - United Provinces of the Rio de la Plata`,
		party: `Unitarian Party`,
		leaning: leanings.LEFT,
		tookOffice: `8 February 1826`,
		leftOffice: `27 June 1827`,
	},
	{
		id: 1025,
		countryId,
		name: `No Leader`,
		party: `None`,
		leaning: leanings.NONE,
		tookOffice: `27 June 1827`,
		leftOffice: `7 July 1827`,
	},
	{
		id: 1026,
		countryId,
		name: `Vicente López y Planes - United Provinces of the Rio de la Plata`,
		party: `Unitarian Party`,
		leaning: leanings.LEFT,
		tookOffice: `7 July 1827`,
		leftOffice: `18 August 1827`,
	},
	{
		id: 1027,
		countryId,
		name: `Manuel Dorrego - United Provinces of the Rio de la Plata`,
		party: `Federalist Party`,
		leaning: leanings.RIGHT,
		tookOffice: `18 August 1827`,
		leftOffice: `1 December 1828`,
	},
	{
		id: 1028,
		countryId,
		name: `Juan Lavalle - United Provinces of the Rio de la Plata`,
		party: `Unitarian Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 December 1828`,
		leftOffice: `26 June 1829`,
	},
	{
		id: 1029,
		countryId,
		name: `Juan José Viamonte - United Provinces of the Rio de la Plata`,
		party: `Federalist Party`,
		leaning: leanings.RIGHT,
		tookOffice: `26 June 1829`,
		leftOffice: `6 December 1829`,
	},
	{
		id: 1030,
		countryId,
		name: `Juan Manuel de Rosas - United Provinces of the Rio de la Plata`,
		party: `Federalist Party`,
		leaning: leanings.RIGHT,
		tookOffice: `6 December 1829`,
		leftOffice: `4 January 1831`,
	},
	{
		id: 1031,
		countryId,
		name: `Juan Manuel de Rosas`,
		party: `Federalist Party`,
		leaning: leanings.RIGHT,
		tookOffice: `4 January 1831`,
		leftOffice: `5 December 1832`,
	},
	{
		id: 1032,
		countryId,
		name: `Juan Ramón Balcarce`,
		party: `Federalist Party`,
		leaning: leanings.RIGHT,
		tookOffice: `5 December 1832`,
		leftOffice: `4 November 1833`,
	},
	{
		id: 1033,
		countryId,
		name: `Juan José Viamonte`,
		party: `Federalist Party`,
		leaning: leanings.RIGHT,
		tookOffice: `4 November 1833`,
		leftOffice: `27 June 1834`,
	},
	{
		id: 1034,
		countryId,
		name: `Manuel Vicente Maza`,
		party: `Federalist Party`,
		leaning: leanings.RIGHT,
		tookOffice: `27 June 1834`,
		leftOffice: `7 March 1835`,
	},
	{
		id: 1035,
		countryId,
		name: `Juan Manuel de Rosas`,
		party: `Federalist Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 March 1835`,
		leftOffice: `3 February 1852`,
	},
	{
		id: 1036,
		countryId,
		name: `Vicente López y Planes`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 February 1852`,
		leftOffice: `6 April 1852`,
	},
	{
		id: 1037,
		countryId,
		name: `Justo José de Urquiza`,
		party: `Federalist Party`,
		leaning: leanings.RIGHT,
		tookOffice: `6 April 1852`,
		leftOffice: `31 May 1852`,
	},
	{
		id: 1038,
		countryId,
		name: `Justo José de Urquiza`,
		party: `Federalist Party`,
		leaning: leanings.RIGHT,
		tookOffice: `31 May 1852`,
		leftOffice: `5 March 1854`,
	},
	{
		id: 1039,
		countryId,
		name: `Justo José de Urquiza`,
		party: `Federalist Party`,
		leaning: leanings.RIGHT,
		tookOffice: `5 March 1854`,
		leftOffice: `5 March 1860`,
	},
	{
		id: 1040,
		countryId,
		name: `Santiago Derqui`,
		party: `Federalist Party`,
		leaning: leanings.RIGHT,
		tookOffice: `5 March 1860`,
		leftOffice: `5 November 1861`,
	},
	{
		id: 1041,
		countryId,
		name: `Juan Esteban Pedernera`,
		party: `Unitarian Party`,
		leaning: leanings.LEFT,
		tookOffice: `5 November 1861`,
		leftOffice: `12 December 1861`,
	},
	{
		id: 1042,
		countryId,
		name: `Bartolomé Mitre`,
		party: `Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 December 1861`,
		leftOffice: `12 October 1868`,
	},
	{
		id: 1043,
		countryId,
		name: `Domingo Faustino Sarmiento`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 October 1868`,
		leftOffice: `12 October 1874`,
	},
	{
		id: 1044,
		countryId,
		name: `Nicolás Avellaneda`,
		party: `National Autonomist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 October 1874`,
		leftOffice: `12 October 1880`,
	},
	{
		id: 1045,
		countryId,
		name: `Alejo Julio Argentino Roca`,
		party: `National Autonomist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 October 1880`,
		leftOffice: `12 October 1886`,
	},
	{
		id: 1046,
		countryId,
		name: `Miguel Ángel Juárez Celman`,
		party: `National Autonomist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 October 1886`,
		leftOffice: `6 August 1890`,
	},
	{
		id: 1047,
		countryId,
		name: `Carlos Pellegrini`,
		party: `National Autonomist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `6 August 1890`,
		leftOffice: `12 October 1892`,
	},
	{
		id: 1048,
		countryId,
		name: `Luis Sáenz Peña`,
		party: `National Autonomist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 October 1892`,
		leftOffice: `22 January 1895`,
	},
	{
		id: 1049,
		countryId,
		name: `José Evaristo Uriburu`,
		party: `National Autonomist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `22 January 1895`,
		leftOffice: `12 October 1898`,
	},
	{
		id: 1050,
		countryId,
		name: `Julio Argentino Roca`,
		party: `National Autonomist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 October 1898`,
		leftOffice: `12 October 1904`,
	},
	{
		id: 1051,
		countryId,
		name: `Manuel Quintana`,
		party: `National Autonomist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 October 1904`,
		leftOffice: `12 March 1906`,
	},
	{
		id: 1052,
		countryId,
		name: `José Figueroa Alcorta`,
		party: `National Autonomist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 March 1906`,
		leftOffice: `12 October 1910`,
	},
	{
		id: 1053,
		countryId,
		name: `Roque Sáenz Peña`,
		party: `National Autonomist Party (Modernist)`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 October 1910`,
		leftOffice: `9 August 1914`,
	},
	{
		id: 1054,
		countryId,
		name: `Victorino de la Plaza`,
		party: `National Autonomist Party (Modernist)`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `9 August 1914`,
		leftOffice: `12 October 1916`,
	},
	{
		id: 1055,
		countryId,
		name: `Hipólito Yrigoyen`,
		party: `Radical Civic Union`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `12 October 1916`,
		leftOffice: `12 October 1922`,
	},
	{
		id: 1056,
		countryId,
		name: `Marcelo Torcuato de Alvear`,
		party: `Radical Civic Union`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `12 October 1922`,
		leftOffice: `12 October 1928`,
	},
	{
		id: 1057,
		countryId,
		name: `Hipólito Yrigoyen`,
		party: `Radical Civic Union`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `12 October 1928`,
		leftOffice: `6 September 1930`,
	},
	{
		id: 1058,
		countryId,
		name: `José Félix Uriburu`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `6 September 1930`,
		leftOffice: `20 February 1932`,
	},
	{
		id: 1059,
		countryId,
		name: `Agustín Pedro Justo`,
		party: `Radical Civic Union (Concordancia)`,
		leaning: leanings.RIGHT,
		tookOffice: `20 February 1932`,
		leftOffice: `20 February 1938`,
	},
	{
		id: 1060,
		countryId,
		name: `Roberto María Ortiz`,
		party: `Radical Civic Union (Concordancia)`,
		leaning: leanings.RIGHT,
		tookOffice: `20 February 1938`,
		leftOffice: `27 June 1942`,
	},
	{
		id: 1061,
		countryId,
		name: `Ramón Castillo`,
		party: `National Democratic Party (Concordancia)`,
		leaning: leanings.RIGHT,
		tookOffice: `27 June 1942`,
		leftOffice: `4 June 1943`,
	},
	{
		id: 1062,
		countryId,
		name: `Arturo Franklin Rawson`,
		party: `Argentine Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `4 June 1943`,
		leftOffice: `7 June 1943`,
	},
	{
		id: 1063,
		countryId,
		name: `Pedro Pablo Ramírez`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `7 June 1943`,
		leftOffice: `9 March 1944`,
	},
	{
		id: 1064,
		countryId,
		name: `Edelmiro Julián Farrell`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `9 March 1944`,
		leftOffice: `4 June 1946`,
	},
	{
		id: 1065,
		countryId,
		name: `Juan Perón`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.RIGHT,
		tookOffice: `4 June 1946`,
		leftOffice: `19 September 1955`,
	},
	{
		id: 1066,
		countryId,
		name: `Eduardo Lonardi`,
		party: `Argentine Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `19 September 1955`,
		leftOffice: `13 November 1955`,
	},

	{
		id: 1067,
		countryId,
		name: `Pedro Eugenio Aramburu`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `13 November 1955`,
		leftOffice: `1 May 1958`,
	},
	{
		id: 1068,
		countryId,
		name: `Arturo Frondizi`,
		party: `Intransigent Radical Civic Union`,
		leaning: leanings.LEFT,
		tookOffice: `1 May 1958`,
		leftOffice: `29 March 1962`,
	},
	{
		id: 1069,
		countryId,
		name: `José María Guido`,
		party: `Intransigent Radical Civic Union`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `29 March 1962`,
		leftOffice: `12 October 1963`,
	},
	{
		id: 1070,
		countryId,
		name: `Arturo Umberto Illia`,
		party: `People's Radical Civic Union`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 October 1963`,
		leftOffice: `28 June 1966`,
	},
	{
		id: 1071,
		countryId,
		name: `Junta of Commanders of the Armed Forces - Pascual Pistarini, Benigno Ignacio Varela, Adolfo Teodoro Álvarez`,
		party: `Argentine Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `28 June 1966`,
		leftOffice: `29 June 1966`,
	},
	{
		id: 1072,
		countryId,
		name: `Juan Carlos Onganía`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `29 June 1966`,
		leftOffice: `8 June 1970`,
	},
	{
		id: 1073,
		countryId,
		name: `Junta of Commanders of the Armed Forces - Pedro Alberto José Gnavi, Alejandro Agustín Lanusse, Carlos Alberto Rey`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `8 June 1970`,
		leftOffice: `18 June 1970`,
	},
	{
		id: 1074,
		countryId,
		name: `Roberto M. Levingston`,
		party: `Argentine Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `18 June 1970`,
		leftOffice: `23 March 1971`,
	},
	{
		id: 1075,
		countryId,
		name: `Junta of Commanders of the Armed Forces - Alejandro Agustín Lanusse, Pedro Alberto José Gnavi, Carlos Alberto Rey`,
		party: `Argentine Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `23 March 1971`,
		leftOffice: `26 March 1971`,
	},
	{
		id: 1076,
		countryId,
		name: `Alejandro Agustín Lanusse`,
		party: `Argentine Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `26 March 1971`,
		leftOffice: `25 May 1973`,
	},
	{
		id: 1077,
		countryId,
		name: `Héctor José Cámpora`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.LEFT,
		tookOffice: `25 May 1973`,
		leftOffice: `13 July 1973`,
	},
	{
		id: 1078,
		countryId,
		name: `Raúl Alberto Lastiri`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.LEFT,
		tookOffice: `13 July 1973`,
		leftOffice: `12 October 1973`,
	},
	{
		id: 1079,
		countryId,
		name: `Juan Perón`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `12 October 1973`,
		leftOffice: `29 June 1974`,
	},
	{
		id: 1080,
		countryId,
		name: `Isabel Perón`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `29 June 1974`,
		leftOffice: `24 March 1976`,
	},
	{
		id: 1081,
		countryId,
		name: `Military Junta - Jorge Rafael Videla, Emilio Eduardo Massera, Orlando Ramón Agosti`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `24 March 1976`,
		leftOffice: `29 March 1976`,
	},
	{
		id: 1082,
		countryId,
		name: `Jorge Rafael Videla`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `29 March 1976`,
		leftOffice: `29 March 1981`,
	},
	{
		id: 1083,
		countryId,
		name: `Roberto Eduardo Viola`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `29 March 1981`,
		leftOffice: `21 November 1981`,
	},
	{
		id: 1084,
		countryId,
		name: `Horacio Tomás Liendo`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `21 November 1981`,
		leftOffice: `11 December 1981`,
	},
	{
		id: 1085,
		countryId,
		name: `Carlos Lacoste`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `11 December 1981`,
		leftOffice: `22 December 1981`,
	},
	{
		id: 1086,
		countryId,
		name: `Leopoldo Galtieri`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `22 December 1981`,
		leftOffice: `18 June 1982`,
	},
	{
		id: 1087,
		countryId,
		name: `Alfredo Oscar Saint Jean`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `18 June 1982`,
		leftOffice: `1 July 1982`,
	},
	{
		id: 1088,
		countryId,
		name: `Reynaldo Bignone`,
		party: `Argentine Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 July 1982`,
		leftOffice: `10 December 1983`,
	},
	{
		id: 1089,
		countryId,
		name: `Raúl Alfonsín`,
		party: `Radical Civic Union`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `10 December 1983`,
		leftOffice: `8 July 1989`,
	},
	{
		id: 1090,
		countryId,
		name: `Carlos Saúl Menem Akil`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.RIGHT,
		tookOffice: `8 July 1989`,
		leftOffice: `10 December 1999`,
	},
	{
		id: 1091,
		countryId,
		name: `Fernando de la Rúa`,
		party: `Alliance for Work, Justice and Education`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 December 1999`,
		leftOffice: `20 December 2001`,
	},
	{
		id: 1092,
		countryId,
		name: `Ramón Puerta`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `20 December 2001`,
		leftOffice: `22 December 2001`,
	},
	{
		id: 1093,
		countryId,
		name: `Adolfo Rodríguez Saá`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `22 December 2001`,
		leftOffice: `30 December 2001`,
	},
	{
		id: 1094,
		countryId,
		name: `Eduardo Camaño`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.CENTRIST,
		tookOffice: `30 December 2001`,
		leftOffice: `2 January 2002`,
	},
	{
		id: 1095,
		countryId,
		name: `Eduardo Duhalde`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.LEFT,
		tookOffice: `2 January 2002`,
		leftOffice: `25 May 2003`,
	},
	{
		id: 1096,
		countryId,
		name: `Néstor Kirchner`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.LEFT,
		tookOffice: `25 May 2003`,
		leftOffice: `10 December 2007`,
	},
	{
		id: 1097,
		countryId,
		name: `Cristina Fernández de Kirchner`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.LEFT,
		tookOffice: `10 December 2007`,
		leftOffice: `10 December 2015`,
	},
	{
		id: 1098,
		countryId,
		name: `Mauricio Macri`,
		party: `Republican Proposal`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 December 2015`,
		leftOffice: `10 December 2019`,
	},
	{
		id: 1099,
		countryId,
		name: `Alberto Fernández`,
		party: `Justicialist Party / Peronist`,
		leaning: leanings.LEFT,
		tookOffice: `10 December 2019`,
		leftOffice: `10 December 2023`,
	},
	{
		id: 1100,
		countryId,
		name: `Javier Milei`,
		party: `Libertarian Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `10 December 2023`,
		leftOffice: null,
	}
];
