import type { LeaderSeed } from '../../src/data/types';
import { leanings } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Chile`;

const countryId = 22;

export const chile: LeaderSeed[] = [
	{
		id: 6000,
		countryId,
		name: `Viceroyalty of Peru`,
		party: `Kingdom of Spain`,
		leaning: leanings.MONARCHY,
		tookOffice: `1 January 1541`,
		leftOffice: `18 September 1810`,
	},
	{
		id: 6001,
		countryId,
		name: `Mateo de Toro y Zambrano`,
		party: `President of the First Government Junta`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 September 1810`,
		leftOffice: `27 February 1811`,
	},
	{
		id: 6002,
		countryId,
		name: `Juan Martínez de Rozas`,
		party: `Interim President of the First Government Junta`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 February 1811`,
		leftOffice: `2 April 1811`,
	},
	{
		id: 6003,
		countryId,
		name: `Fernando Márquez de la Plata`,
		party: `President of the First Government Junta`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 April 1811`,
		leftOffice: `4 July 1811`,
	},
	{
		id: 6004,
		countryId,
		name: `Juan Antonio Ovalle`,
		party: `President of the First National Congress`,
		leaning: leanings.CENTRIST,
		tookOffice: `4 July 1811`,
		leftOffice: `20 July 1811`,
	},
	{
		id: 6005,
		countryId,
		name: `Martín Calvo Encalada`,
		party: `President of the Provisional Executive Authority`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 July 1811`,
		leftOffice: `4 September 1811`,
	},
	{
		id: 6006,
		countryId,
		name: `Juan Enrique Rosales`,
		party: `President of the Executive Court`,
		leaning: leanings.CENTRIST,
		tookOffice: `4 September 1811`,
		leftOffice: `16 November 1811`,
	},
	{
		id: 6007,
		countryId,
		name: `José Miguel Carrera`,
		party: `President of the Provisional Government Junta`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 November 1811`,
		leftOffice: `8 April 1812`,
	},
	{
		id: 6008,
		countryId,
		name: `José Santiago Portales y Larraín`,
		party: `President of the Provisional Government Junta`,
		leaning: leanings.CENTRIST,
		tookOffice: `8 April 1812`,
		leftOffice: `6 August 1812`,
	},
	{
		id: 6009,
		countryId,
		name: `Pedro José Prado Jaraquemada`,
		party: `President of the Provisional Government Junta`,
		leaning: leanings.CENTRIST,
		tookOffice: `6 August 1812`,
		leftOffice: `6 December 1812`,
	},
	{
		id: 6010,
		countryId,
		name: `José Miguel Carrera`,
		party: `President of the Provisional Government Junta`,
		leaning: leanings.CENTRIST,
		tookOffice: `6 December 1812`,
		leftOffice: `30 March 1813`,
	},
	{
		id: 6011,
		countryId,
		name: `Juan José Carrera`,
		party: `President of the Provisional Government Junta`,
		leaning: leanings.CENTRIST,
		tookOffice: `30 March 1813`,
		leftOffice: `13 April 1813`,
	},
	{
		id: 6012,
		countryId,
		name: `Francisco Antonio Pérez`,
		party: `President of the Superior Governmental Junta`,
		leaning: leanings.CENTRIST,
		tookOffice: `13 April 1813`,
		leftOffice: `23 August 1813`,
	},
	{
		id: 6013,
		countryId,
		name: `José Miguel Infante`,
		party: `President of the Superior Governmental Junta`,
		leaning: leanings.CENTRIST,
		tookOffice: `23 August 1813`,
		leftOffice: `11 January 1814`,
	},
	{
		id: 6014,
		countryId,
		name: `Agustín Eyzaguirre`,
		party: `President of the Superior Governmental Junta`,
		leaning: leanings.CENTRIST,
		tookOffice: `11 January 1814`,
		leftOffice: `7 March 1814`,
	},
	{
		id: 6015,
		countryId,
		name: `Antonio José de Irisarri`,
		party: `Interim Supreme Director`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 March 1814`,
		leftOffice: `14 March 1814`,
	},
	{
		id: 6016,
		countryId,
		name: `Francisco de la Lastra`,
		party: `Supreme Director`,
		leaning: leanings.CENTRIST,
		tookOffice: `14 March 1814`,
		leftOffice: `23 July 1814`,
	},
	{
		id: 6017,
		countryId,
		name: `José Miguel Carrera`,
		party: `President of the Government Junta`,
		leaning: leanings.CENTRIST,
		tookOffice: `23 July 1814`,
		leftOffice: `3 October 1814`,
	},
	{
		id: 6018,
		countryId,
		name: `Mariano Osorio`,
		party: `Royal Governor`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 October 1814`,
		leftOffice: `26 December 1815`,
	},
	{
		id: 6019,
		countryId,
		name: `Casimiro Marcó del Pont`,
		party: `Royal Governor`,
		leaning: leanings.CENTRIST,
		tookOffice: `26 December 1815`,
		leftOffice: `12 February 1817`,
	},
	{
		id: 6020,
		countryId,
		name: `Bernardo O'Higgins`,
		party: `Supreme Director`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 February 1817`,
		leftOffice: `28 January 1823`,
	},
	{
		id: 6021,
		countryId,
		name: `Agustín Eyzaguirre`,
		party: `President of the Government Junta`,
		leaning: leanings.CENTRIST,
		tookOffice: `28 January 1823`,
		leftOffice: `4 April 1823`,
	},
	{
		id: 6022,
		countryId,
		name: `Ramón Freire`,
		party: `Interim Supreme Director`,
		leaning: leanings.LEFT,
		tookOffice: `4 April 1823`,
		leftOffice: `9 July 1826`,
	},
	{
		id: 6023,
		countryId,
		name: `Manuel Blanco Encalada`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `9 July 1826`,
		leftOffice: `9 September 1826`,
	},
	{
		id: 6024,
		countryId,
		name: `Agustín Eyzaguirre`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `9 September 1826`,
		leftOffice: `25 January 1827`,
	},
	{
		id: 6025,
		countryId,
		name: `Ramón Freire`,
		party: `Pipiolos`,
		leaning: leanings.LEFT,
		tookOffice: `25 January 1827`,
		leftOffice: `15 February 1827`,
	},
	{
		id: 6026,
		countryId,
		name: `Francisco Antonio Pinto`,
		party: `Pipiolos`,
		leaning: leanings.LEFT,
		tookOffice: `8 May 1827`,
		leftOffice: `16 July 1829`,
	},
	{
		id: 6027,
		countryId,
		name: `Francisco Ramón Vicuña`,
		party: `Pipiolos`,
		leaning: leanings.LEFT,
		tookOffice: `16 July 1829`,
		leftOffice: `19 October 1829`,
	},
	{
		id: 6028,
		countryId,
		name: `Francisco Antonio Pinto`,
		party: `Pipiolos`,
		leaning: leanings.LEFT,
		tookOffice: `19 October 1829`,
		leftOffice: `2 November 1829`,
	},
	{
		id: 6029,
		countryId,
		name: `Francisco Ramón Vicuña`,
		party: `Pipiolos`,
		leaning: leanings.LEFT,
		tookOffice: `2 November 1829`,
		leftOffice: `7 November 1829`,
	},
	{
		id: 6030,
		countryId,
		name: `Ramón Freire`,
		party: `Pipiolos`,
		leaning: leanings.LEFT,
		tookOffice: `7 November 1829`,
		leftOffice: `8 November 1829`,
	},
	{
		id: 6031,
		countryId,
		name: `Francisco Ramón Vicuña`,
		party: `Pipiolos`,
		leaning: leanings.LEFT,
		tookOffice: `8 November 1829`,
		leftOffice: `7 December 1829`,
	},
	{
		id: 6032,
		countryId,
		name: `José Tomás Ovalle y Bezanilla`,
		party: `Pelucones`,
		leaning: leanings.RIGHT,
		tookOffice: `24 December 1829`,
		leftOffice: `18 February 1830`,
	},
	{
		id: 6033,
		countryId,
		name: `Francisco Ruiz-Tagle Portales`,
		party: `Pelucones`,
		leaning: leanings.RIGHT,
		tookOffice: `18 February 1830`,
		leftOffice: `1 April 1830`,
	},
	{
		id: 6034,
		countryId,
		name: `José Tomás Ovalle y Bezanilla`,
		party: `Pelucones`,
		leaning: leanings.RIGHT,
		tookOffice: `1 April 1830`,
		leftOffice: `8 March 1831`,
	},
	{
		id: 6035,
		countryId,
		name: `Fernando Errázuriz Aldunate`,
		party: `Pelucones`,
		leaning: leanings.RIGHT,
		tookOffice: `8 March 1831`,
		leftOffice: `18 September 1831`,
	},
	{
		id: 6036,
		countryId,
		name: `Joaquín Prieto`,
		party: `Pelucones`,
		leaning: leanings.RIGHT,
		tookOffice: `18 September 1831`,
		leftOffice: `18 September 1836`,
	},
	{
		id: 6037,
		countryId,
		name: `Joaquín Prieto`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `18 September 1836`,
		leftOffice: `18 September 1841`,
	},
	{
		id: 6038,
		countryId,
		name: `Manuel Bulnes`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `18 September 1841`,
		leftOffice: `18 September 1851`,
	},
	{
		id: 6039,
		countryId,
		name: `Manuel Montt`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `18 September 1851`,
		leftOffice: `18 September 1856`,
	},
	{
		id: 6040,
		countryId,
		name: `Manuel Montt`,
		party: `National Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `18 September 1856`,
		leftOffice: `18 September 1861`,
	},
	{
		id: 6041,
		countryId,
		name: `José Joaquín Pérez`,
		party: `National Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `18 September 1861`,
		leftOffice: `18 September 1871`,
	},
	{
		id: 6042,
		countryId,
		name: `Federico Errázuriz Zañartu`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `18 September 1871`,
		leftOffice: `18 September 1876`,
	},
	{
		id: 6043,
		countryId,
		name: `Aníbal Pinto`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `18 September 1876`,
		leftOffice: `18 September 1881`,
	},
	{
		id: 6044,
		countryId,
		name: `Domingo Santa María`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `18 September 1881`,
		leftOffice: `18 September 1886`,
	},
	{
		id: 6045,
		countryId,
		name: `José Manuel Balmaceda`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `18 September 1886`,
		leftOffice: `29 August 1891`,
	},
	{
		id: 6046,
		countryId,
		name: `Claudio Vicuña Guerrero`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `29 August 1891`,
		leftOffice: `29 August 1891`,
	},
	{
		id: 6047,
		countryId,
		name: `Manuel Baquedano`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `29 August 1891`,
		leftOffice: `31 August 1891`,
	},
	{
		id: 6048,
		countryId,
		name: `Jorge Montt`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `31 August 1891`,
		leftOffice: `26 December 1891`,
	},
	{
		id: 6049,
		countryId,
		name: `Jorge Montt`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `26 December 1891`,
		leftOffice: `18 September 1896`,
	},
	{
		id: 6050,
		countryId,
		name: `Federico Errázuriz Echaurren`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `18 September 1896`,
		leftOffice: `12 July 1901`,
	},
	{
		id: 6051,
		countryId,
		name: `Aníbal Zañartu`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 July 1901`,
		leftOffice: `18 September 1901`,
	},
	{
		id: 6052,
		countryId,
		name: `Germán Riesco`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `18 September 1901`,
		leftOffice: `18 September 1906`,
	},
	{
		id: 6053,
		countryId,
		name: `Pedro Montt`,
		party: `National Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `18 September 1906`,
		leftOffice: `16 August 1910`,
	},
	{
		id: 6054,
		countryId,
		name: `Elías Fernández Albano`,
		party: `National Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `16 August 1910`,
		leftOffice: `6 September 1910`,
	},
	{
		id: 6055,
		countryId,
		name: `Emiliano Figueroa`,
		party: `Liberal Democratic Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `6 September 1910`,
		leftOffice: `23 December 1910`,
	},
	{
		id: 6056,
		countryId,
		name: `Ramón Barros Luco`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `23 December 1910`,
		leftOffice: `23 December 1915`,
	},
	{
		id: 6057,
		countryId,
		name: `Juan Luis Sanfuentes`,
		party: `Liberal Democratic Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `23 December 1915`,
		leftOffice: `23 December 1920`,
	},
	{
		id: 6058,
		countryId,
		name: `Arturo Alessandri`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `23 December 1920`,
		leftOffice: `12 September 1924`,
	},
	{
		id: 6059,
		countryId,
		name: `Luis Altamirano`,
		party: `Military`,
		leaning: leanings.RIGHT,
		tookOffice: `12 September 1924`,
		leftOffice: `23 January 1925`,
	},
	{
		id: 6060,
		countryId,
		name: `Pedro Dartnell`,
		party: `Military`,
		leaning: leanings.RIGHT,
		tookOffice: `23 January 1925`,
		leftOffice: `27 January 1925`,
	},
	{
		id: 6061,
		countryId,
		name: `Emilio Bello Codesido`,
		party: `Liberal Democratic Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 January 1925`,
		leftOffice: `12 March 1925`,
	},
	{
		id: 6062,
		countryId,
		name: `Arturo Alessandri`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 March 1925`,
		leftOffice: `1 October 1925`,
	},
	{
		id: 6063,
		countryId,
		name: `Luis Barros Borgoño`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 October 1925`,
		leftOffice: `23 December 1925`,
	},
	{
		id: 6064,
		countryId,
		name: `Emiliano Figueroa`,
		party: `Liberal Democratic Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `23 December 1925`,
		leftOffice: `10 May 1927`,
	},
	{
		id: 6065,
		countryId,
		name: `Carlos Ibáñez del Campo`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 May 1927`,
		leftOffice: `26 July 1931`,
	},
	{
		id: 6066,
		countryId,
		name: `Pedro Opaso`,
		party: `Liberal Democratic Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `26 July 1931`,
		leftOffice: `27 July 1931`,
	},
	{
		id: 6067,
		countryId,
		name: `Juan Esteban Montero`,
		party: `Radical Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `27 July 1931`,
		leftOffice: `20 August 1931`,
	},
	{
		id: 6068,
		countryId,
		name: `Manuel Trucco`,
		party: `Radical Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `20 August 1931`,
		leftOffice: `15 November 1931`,
	},
	{
		id: 6069,
		countryId,
		name: `Juan Esteban Montero`,
		party: `Radical Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `15 November 1931`,
		leftOffice: `4 June 1932`,
	},
	{
		id: 6070,
		countryId,
		name: `Arturo Puga`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `4 June 1932`,
		leftOffice: `16 June 1932`,
	},
	{
		id: 6071,
		countryId,
		name: `Carlos Dávila`,
		party: `Socialist Party`,
		leaning: leanings.LEFT,
		tookOffice: `16 June 1932`,
		leftOffice: `13 September 1932`,
	},
	{
		id: 6072,
		countryId,
		name: `Bartolomé Blanche`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `13 September 1932`,
		leftOffice: `2 October 1932`,
	},
	{
		id: 6073,
		countryId,
		name: `Abraham Oyanedel`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 October 1932`,
		leftOffice: `24 December 1932`,
	},
	{
		id: 6074,
		countryId,
		name: `Arturo Alessandri`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `24 December 1932`,
		leftOffice: `24 December 1938`,
	},
	{
		id: 6075,
		countryId,
		name: `Pedro Aguirre Cerda`,
		party: `Radical Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `24 December 1938`,
		leftOffice: `25 November 1941`,
	},
	{
		id: 6076,
		countryId,
		name: `Jerónimo Méndez`,
		party: `Radical Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `25 November 1941`,
		leftOffice: `2 April 1942`,
	},
	{
		id: 6077,
		countryId,
		name: `Juan Antonio Ríos`,
		party: `Radical Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `2 April 1942`,
		leftOffice: `27 June 1946`,
	},
	{
		id: 6078,
		countryId,
		name: `Alfredo Duhalde`,
		party: `Radical Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `27 June 1946`,
		leftOffice: `3 August 1946`,
	},
	{
		id: 6079,
		countryId,
		name: `Vicente Merino`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 August 1946`,
		leftOffice: `13 August 1946`,
	},
	{
		id: 6080,
		countryId,
		name: `Alfredo Duhalde`,
		party: `Radical Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `13 August 1946`,
		leftOffice: `17 October 1946`,
	},
	{
		id: 6081,
		countryId,
		name: `Juan Antonio Iribarren`,
		party: `Radical Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `17 October 1946`,
		leftOffice: `3 November 1946`,
	},
	{
		id: 6082,
		countryId,
		name: `Gabriel González Videla`,
		party: `Radical Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `3 November 1946`,
		leftOffice: `3 November 1952`,
	},
	{
		id: 6083,
		countryId,
		name: `Carlos Ibáñez del Campo`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 November 1952`,
		leftOffice: `3 November 1958`,
	},
	{
		id: 6084,
		countryId,
		name: `Jorge Alessandri`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 November 1958`,
		leftOffice: `3 November 1964`,
	},
	{
		id: 6085,
		countryId,
		name: `Eduardo Frei Montalva`,
		party: `Christian Democratic Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `3 November 1964`,
		leftOffice: `3 November 1970`,
	},
	{
		id: 6086,
		countryId,
		name: `Salvador Allende`,
		party: `Socialist Party`,
		leaning: leanings.LEFT,
		tookOffice: `3 November 1970`,
		leftOffice: `11 September 1973`,
	},
	{
		id: 6087,
		countryId,
		name: `Augusto Pinochet`,
		party: `Military`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `11 September 1973`,
		leftOffice: `11 March 1990`,
	},
	{
		id: 6088,
		countryId,
		name: `Patricio Aylwin`,
		party: `Christian Democratic Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `11 March 1990`,
		leftOffice: `11 March 1994`,
	},
	{
		id: 6089,
		countryId,
		name: `Eduardo Frei Ruiz-Tagle`,
		party: `Christian Democratic Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `11 March 1994`,
		leftOffice: `11 March 2000`,
	},
	{
		id: 6090,
		countryId,
		name: `Ricardo Lagos`,
		party: `Party for Democracy`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `11 March 2000`,
		leftOffice: `11 March 2006`,
	},
	{
		id: 6091,
		countryId,
		name: `Michelle Bachelet`,
		party: `Socialist Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `11 March 2006`,
		leftOffice: `11 March 2010`,
	},
	{
		id: 6092,
		countryId,
		name: `Sebastián Piñera`,
		party: `National Renewal`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `11 March 2010`,
		leftOffice: `11 March 2014`,
	},
	{
		id: 6093,
		countryId,
		name: `Michelle Bachelet`,
		party: `Socialist Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `11 March 2014`,
		leftOffice: `11 March 2018`,
	},
	{
		id: 6094,
		countryId,
		name: `Sebastián Piñera`,
		party: `Chile Vamos`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `11 March 2018`,
		leftOffice: `11 March 2022`,
	},
	{
		id: 6095,
		countryId,
		name: `Gabriel Boric`,
		party: `Social Convergence`,
		leaning: leanings.LEFT,
		tookOffice: `11 March 2022`,
		leftOffice: `11 March 2026`,
	},
	{
		id: 6096,
		countryId,
		name: `José Antonio Kast`,
		party: `Republican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `11 March 2026`,
		leftOffice: null,
	},
];
