import type { LeaderSeed } from '../../src/data/types';
import { leanings } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_the_Dominican_Republic`;

const countryId = 27;

export const dominicanRepublic: LeaderSeed[] = [
	{
		id: 10000,
		countryId,
		name: `Captaincy General of Santo Domingo`,
		party: `Kingdom of Spain`,
		leaning: leanings.MONARCHY,
		tookOffice: `1 January 1535`,
		leftOffice: `22 July 1795`,
	},
	{
		id: 10001,
		countryId,
		name: `French Santo Domingo`,
		party: `French Empire`,
		leaning: leanings.MONARCHY,
		tookOffice: `22 July 1795`,
		leftOffice: `9 July 1809`,
	},
	{
		id: 10002,
		countryId,
		name: `España Boba`,
		party: `Kingdom of Spain`,
		leaning: leanings.MONARCHY,
		tookOffice: `9 July 1809`,
		leftOffice: `1 December 1821`,
	},
	{
		id: 10003,
		countryId,
		name: `Independent State of Spanish Haiti`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 December 1821`,
		leftOffice: `9 February 1822`,
	},
	{
		id: 10004,
		countryId,
		name: `Haitian Occupation of Santo Domingo`,
		party: `Republic of Haiti`,
		leaning: leanings.MILITARY,
		tookOffice: `9 February 1822`,
		leftOffice: `27 February 1844`,
	},
	{
		id: 10005,
		countryId,
		name: `Tomás Bobadilla`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 February 1844`,
		leftOffice: `9 June 1844`,
	},
	{
		id: 10006,
		countryId,
		name: `Francisco del Rosario Sánchez`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `9 June 1844`,
		leftOffice: `12 July 1844`,
	},
	{
		id: 10007,
		countryId,
		name: `Pedro Santana`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 July 1844`,
		leftOffice: `14 November 1844`,
	},
	{
		id: 10008,
		countryId,
		name: `Pedro Santana`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `14 November 1844`,
		leftOffice: `4 August 1848`,
	},
	{
		id: 10009,
		countryId,
		name: `No Leader`,
		party: `None`,
		leaning: leanings.NONE,
		tookOffice: `4 August 1848`,
		leftOffice: `8 September 1848`,
	},
	{
		id: 10010,
		countryId,
		name: `Manuel Jimenes`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `8 September 1848`,
		leftOffice: `30 May 1849`,
	},
	{
		id: 10011,
		countryId,
		name: `Pedro Santana`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `30 May 1849`,
		leftOffice: `24 September 1849`,
	},
	{
		id: 10012,
		countryId,
		name: `Buenaventura Báez`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `24 September 1849`,
		leftOffice: `15 February 1853`,
	},
	{
		id: 10013,
		countryId,
		name: `Pedro Santana`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 February 1853`,
		leftOffice: `26 May 1856`,
	},
	{
		id: 10014,
		countryId,
		name: `Manuel de Regla Mota`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `26 May 1856`,
		leftOffice: `8 October 1856`,
	},
	{
		id: 10015,
		countryId,
		name: `Buenaventura Báez`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `8 October 1856`,
		leftOffice: `7 July 1857`,
	},
	{
		id: 10016,
		countryId,
		name: `José Desiderio Valverde`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 July 1857`,
		leftOffice: `13 June 1858`,
	},
	{
		id: 10017,
		countryId,
		name: `Pedro Santana`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `13 June 1858`,
		leftOffice: `31 January 1859`,
	},
	{
		id: 10018,
		countryId,
		name: `Pedro Santana`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `31 January 1859`,
		leftOffice: `18 March 1861`,
	},
	{
		id: 10019,
		countryId,
		name: `Pedro Santana`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 March 1861`,
		leftOffice: `20 July 1862`,
	},
	{
		id: 10020,
		countryId,
		name: `Felipe Ribero y Lemoine`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 July 1862`,
		leftOffice: `14 September 1863`,
	},
	{
		id: 10021,
		countryId,
		name: `José Antonio Salcedo`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `14 September 1863`,
		leftOffice: `10 October 1864`,
	},
	{
		id: 10022,
		countryId,
		name: `Gaspar Polanco`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 October 1864`,
		leftOffice: `24 January 1865`,
	},
	{
		id: 10023,
		countryId,
		name: `Benigno Filomeno de Rojas`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `24 January 1865`,
		leftOffice: `25 March 1865`,
	},
	{
		id: 10024,
		countryId,
		name: `Pedro Antonio Pimentel`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 March 1865`,
		leftOffice: `11 July 1865`,
	},
	{
		id: 10025,
		countryId,
		name: `Pedro Antonio Pimentel`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `11 July 1865`,
		leftOffice: `4 August 1865`,
	},
	{
		id: 10026,
		countryId,
		name: `José María Cabral`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `4 August 1865`,
		leftOffice: `15 November 1865`,
	},
	{
		id: 10027,
		countryId,
		name: `Pedro Guillermo`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 November 1865`,
		leftOffice: `8 December 1865`,
	},
	{
		id: 10028,
		countryId,
		name: `Buenaventura Báez`,
		party: `Red Party`,
		leaning: leanings.RIGHT,
		tookOffice: `8 December 1865`,
		leftOffice: `29 May 1866`,
	},
	{
		id: 10029,
		countryId,
		name: `Triumvirate`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `29 May 1866`,
		leftOffice: `22 August 1866`,
	},
	{
		id: 10030,
		countryId,
		name: `José María Cabral`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `22 August 1866`,
		leftOffice: `29 September 1866`,
	},
	{
		id: 10031,
		countryId,
		name: `José María Cabral`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `29 September 1866`,
		leftOffice: `31 January 1868`,
	},
	{
		id: 10032,
		countryId,
		name: `Manuel Altagracia Cáceres`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `31 January 1868`,
		leftOffice: `13 February 1868`,
	},
	{
		id: 10033,
		countryId,
		name: `Junta of Generals`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `13 February 1868`,
		leftOffice: `2 May 1868`,
	},
	{
		id: 10034,
		countryId,
		name: `Buenaventura Báez`,
		party: `Red Party`,
		leaning: leanings.RIGHT,
		tookOffice: `2 May 1868`,
		leftOffice: `25 November 1873`,
	},
	{
		id: 10035,
		countryId,
		name: `Ignacio María González`,
		party: `Green Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 November 1873`,
		leftOffice: `21 January 1874`,
	},
	{
		id: 10036,
		countryId,
		name: `Ignacio María González`,
		party: `Green Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `21 January 1874`,
		leftOffice: `5 February 1874`,
	},
	{
		id: 10037,
		countryId,
		name: `Ignacio María González`,
		party: `Green Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 February 1874`,
		leftOffice: `23 February 1876`,
	},
	{
		id: 10038,
		countryId,
		name: `Council of Secretaries of State`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `23 February 1876`,
		leftOffice: `29 April 1876`,
	},
	{
		id: 10039,
		countryId,
		name: `Ulises Francisco Espaillat`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `29 April 1876`,
		leftOffice: `5 October 1876`,
	},
	{
		id: 10040,
		countryId,
		name: `Superior Governing Junta`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 October 1876`,
		leftOffice: `11 November 1876`,
	},
	{
		id: 10041,
		countryId,
		name: `Ignacio María González`,
		party: `Green Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `11 November 1876`,
		leftOffice: `10 December 1876`,
	},
	{
		id: 10042,
		countryId,
		name: `Marcos Antonio Cabral`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 December 1876`,
		leftOffice: `27 December 1876`,
	},
	{
		id: 10043,
		countryId,
		name: `Buenaventura Báez`,
		party: `Red Party`,
		leaning: leanings.RIGHT,
		tookOffice: `27 December 1876`,
		leftOffice: `1 March 1878`,
	},
	{
		id: 10044,
		countryId,
		name: `Ignacio María González`,
		party: `Green Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1878`,
		leftOffice: `2 March 1878`,
	},
	{
		id: 10045,
		countryId,
		name: `Council of Secretaries of State`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 March 1878`,
		leftOffice: `5 March 1878`,
	},
	{
		id: 10046,
		countryId,
		name: `Cesáreo Guillermo`,
		party: `Red Party`,
		leaning: leanings.RIGHT,
		tookOffice: `5 March 1878`,
		leftOffice: `6 July 1878`,
	},
	{
		id: 10047,
		countryId,
		name: `Ignacio María González`,
		party: `Green Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `6 July 1878`,
		leftOffice: `2 September 1878`,
	},
	{
		id: 10048,
		countryId,
		name: `Superior Leaders of the Revolutionary Movement`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 September 1878`,
		leftOffice: `7 September 1878`,
	},
	{
		id: 10049,
		countryId,
		name: `Jacinto de Castro`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 September 1878`,
		leftOffice: `30 September 1878`,
	},
	{
		id: 10050,
		countryId,
		name: `Council of Secretaries of State`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `30 September 1878`,
		leftOffice: `27 February 1879`,
	},
	{
		id: 10051,
		countryId,
		name: `Cesáreo Guillermo`,
		party: `Red Party`,
		leaning: leanings.RIGHT,
		tookOffice: `27 February 1879`,
		leftOffice: `6 October 1879`,
	},
	{
		id: 10052,
		countryId,
		name: `Gregorio Luperón`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `6 October 1879`,
		leftOffice: `1 September 1880`,
	},
	{
		id: 10053,
		countryId,
		name: `Fernando Arturo de Meriño`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 September 1880`,
		leftOffice: `1 September 1882`,
	},
	{
		id: 10054,
		countryId,
		name: `Ulises Heureaux`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 September 1882`,
		leftOffice: `1 September 1884`,
	},
	{
		id: 10055,
		countryId,
		name: `Francisco Gregorio Billini`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 September 1884`,
		leftOffice: `16 May 1885`,
	},
	{
		id: 10056,
		countryId,
		name: `Alejandro Woss y Gil`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 May 1885`,
		leftOffice: `6 January 1887`,
	},
	{
		id: 10057,
		countryId,
		name: `Ulises Heureaux`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `6 January 1887`,
		leftOffice: `27 February 1889`,
	},
	{
		id: 10058,
		countryId,
		name: `Ulises Heureaux`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 February 1889`,
		leftOffice: `27 February 1893`,
	},
	{
		id: 10059,
		countryId,
		name: `Ulises Heureaux`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 February 1893`,
		leftOffice: `27 February 1897`,
	},
	{
		id: 10060,
		countryId,
		name: `Ulises Heureaux`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 February 1897`,
		leftOffice: `26 July 1899`,
	},
	{
		id: 10061,
		countryId,
		name: `Wenceslao Figuereo`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `26 July 1899`,
		leftOffice: `30 August 1899`,
	},
	{
		id: 10062,
		countryId,
		name: `Horacio Vásquez`,
		party: `Red Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `30 August 1899`,
		leftOffice: `15 November 1899`,
	},
	{
		id: 10063,
		countryId,
		name: `Juan Isidro Jimenes`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 November 1899`,
		leftOffice: `2 May 1902`,
	},
	{
		id: 10064,
		countryId,
		name: `Horacio Vásquez`,
		party: `Red Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `2 May 1902`,
		leftOffice: `23 April 1903`,
	},
	{
		id: 10065,
		countryId,
		name: `Alejandro Woss y Gil`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `23 April 1903`,
		leftOffice: `24 November 1903`,
	},
	{
		id: 10066,
		countryId,
		name: `Carlos Felipe Morales Languasco`,
		party: `Red Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `24 November 1903`,
		leftOffice: `25 December 1905`,
	},
	{
		id: 10067,
		countryId,
		name: `Council of Secretaries of State`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 December 1905`,
		leftOffice: `29 December 1905`,
	},
	{
		id: 10068,
		countryId,
		name: `Ramón Cáceres`,
		party: `Red Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `29 December 1905`,
		leftOffice: `19 November 1911`,
	},
	{
		id: 10069,
		countryId,
		name: `Council of Secretaries of State`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `19 November 1911`,
		leftOffice: `5 December 1911`,
	},
	{
		id: 10070,
		countryId,
		name: `Eladio Victoria`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 December 1911`,
		leftOffice: `1 December 1912`,
	},
	{
		id: 10071,
		countryId,
		name: `Adolfo Alejandro Nouel`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 December 1912`,
		leftOffice: `13 April 1913`,
	},
	{
		id: 10072,
		countryId,
		name: `José Bordas Valdez`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `13 April 1913`,
		leftOffice: `27 August 1914`,
	},
	{
		id: 10073,
		countryId,
		name: `Ramón Báez`,
		party: `Indepedent`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 August 1914`,
		leftOffice: `5 December 1914`,
	},
	{
		id: 10074,
		countryId,
		name: `Juan Isidro Jimenes Pereyra`,
		party: `Blue Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 December 1914`,
		leftOffice: `4 May 1916`,
	},
	{
		id: 10075,
		countryId,
		name: `United States Occupation of the Dominican Republic`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `4 May 1916`,
		leftOffice: `24 July 1924`,
	},
	{
		id: 10076,
		countryId,
		name: `Horacio Vásquez`,
		party: `Red Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `24 July 1924`,
		leftOffice: `3 March 1930`,
	},
	{
		id: 10077,
		countryId,
		name: `Rafael Trujillo`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `3 March 1930`,
		leftOffice: `30 May 1961`,
	},
	{
		id: 10078,
		countryId,
		name: `Joaquín Balaguer`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `30 May 1961`,
		leftOffice: `1 January 1962`,
	},
	{
		id: 10079,
		countryId,
		name: `Civic-Military Council`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 January 1962`,
		leftOffice: `18 January 1962`,
	},
	{
		id: 10080,
		countryId,
		name: `Rafael Bonnelly`,
		party: `Dominican Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `18 January 1962`,
		leftOffice: `27 February 1963`,
	},
	{
		id: 10081,
		countryId,
		name: `Juan Bosch`,
		party: `Dominican Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `27 February 1963`,
		leftOffice: `25 September 1963`,
	},
	{
		id: 10082,
		countryId,
		name: `Víctor Elby Viñas Román`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 September 1963`,
		leftOffice: `26 September 1963`,
	},
	{
		id: 10083,
		countryId,
		name: `Triumvirate`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `26 September 1963`,
		leftOffice: `25 April 1965`,
	},
	{
		id: 10084,
		countryId,
		name: `José Rafael Molina Ureña`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 April 1965`,
		leftOffice: `7 May 1965`,
	},
	{
		id: 10085,
		countryId,
		name: `Antonio Imbert`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 May 1965`,
		leftOffice: `3 September 1965`,
	},
	{
		id: 10086,
		countryId,
		name: `Héctor Rafael García-Godoy Cáceres`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 September 1965`,
		leftOffice: `1 July 1966`,
	},
	{
		id: 10087,
		countryId,
		name: `Joaquín Balaguer`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 July 1966`,
		leftOffice: `16 August 1978`,
	},
	{
		id: 10088,
		countryId,
		name: `Silvestre Antonio Guzmán Fernández`,
		party: `Dominican Dominican Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `16 August 1978`,
		leftOffice: `4 July 1982`,
	},
	{
		id: 10089,
		countryId,
		name: `Jacobo Majluta Azar`,
		party: `Dominican Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `4 July 1982`,
		leftOffice: `16 August 1982`,
	},
	{
		id: 10090,
		countryId,
		name: `Salvador Jorge Blanco`,
		party: `Dominican Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `16 August 1982`,
		leftOffice: `16 August 1986`,
	},
	{
		id: 10091,
		countryId,
		name: `Joaquín Balaguer`,
		party: `Dominican Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `16 August 1986`,
		leftOffice: `16 August 1996`,
	},
	{
		id: 10092,
		countryId,
		name: `Leonel Fernández`,
		party: `Dominican Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `16 August 1996`,
		leftOffice: `16 August 2000`,
	},
	{
		id: 10093,
		countryId,
		name: `Hipólito Mejía`,
		party: `Dominican Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 August 2000`,
		leftOffice: `16 August 2004`,
	},
	{
		id: 10094,
		countryId,
		name: `Leonel Fernández`,
		party: `Dominican Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `16 August 2004`,
		leftOffice: `16 August 2012`,
	},
	{
		id: 10095,
		countryId,
		name: `Danilo Medina`,
		party: `Dominican Liberation Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `16 August 2012`,
		leftOffice: `16 August 2020`,
	},
	{
		id: 10096,
		countryId,
		name: `Luis Abinader`,
		party: `Modern Dominican Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 August 2020`,
		leftOffice: null,
	},
];
