import type { LeaderSeed } from '../../src/data/types';
import { leanings } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Ecuador`;

const countryId = 12;

export const ecuador: LeaderSeed[] = [
	{
		id: 11000,
		countryId,
		name: `Viceroyalty of New Granada`,
		party: `Kingdom of Spain`,
		leaning: leanings.MONARCHY,
		tookOffice: `27 May 1717`,
		leftOffice: `24 May 1822`,
	},
	{
		id: 11001,
		countryId,
		name: `Simón Bolívar - Gran Colombia`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `24 May 1822`,
		leftOffice: `3 May 1830`,
	},
	{
		id: 11002,
		countryId,
		name: `Juan José Flores`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `3 May 1830`,
		leftOffice: `10 September 1834`,
	},
	{
		id: 11003,
		countryId,
		name: `Vicente Rocafuerte`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `10 September 1834`,
		leftOffice: `1 February 1839`,
	},
	{
		id: 11004,
		countryId,
		name: `Juan José Flores`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `1 February 1839`,
		leftOffice: `7 March 1845`,
	},
	{
		id: 11005,
		countryId,
		name: `José Joaquín de Olmedo`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `7 March 1845`,
		leftOffice: `8 December 1845`,
	},
	{
		id: 11006,
		countryId,
		name: `Vicente Ramón Roca`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `8 December 1845`,
		leftOffice: `15 October 1849`,
	},
	{
		id: 11007,
		countryId,
		name: `Manuel de Ascásubi`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `15 October 1849`,
		leftOffice: `8 December 1850`,
	},
	{
		id: 11008,
		countryId,
		name: `Diego Noboa`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `8 December 1850`,
		leftOffice: `12 September 1851`,
	},
	{
		id: 11009,
		countryId,
		name: `José María Urvina`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `24 July 1851`,
		leftOffice: `16 October 1856`,
	},
	{
		id: 11010,
		countryId,
		name: `Francisco Robles`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `16 October 1856`,
		leftOffice: `31 August 1859`,
	},
	{
		id: 11011,
		countryId,
		name: `Governments of The Crisis`,
		party: `Mixed`,
		leaning: leanings.CENTRIST,
		tookOffice: `4 September 1859`,
		leftOffice: `10 January 1861`,
	},
	{
		id: 11012,
		countryId,
		name: `Gabriel García Moreno`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `17 January 1861`,
		leftOffice: `31 August 1865`,
	},
	{
		id: 11013,
		countryId,
		name: `Rafael Carvajal`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `31 August 1865`,
		leftOffice: `7 September 1865`,
	},
	{
		id: 11014,
		countryId,
		name: `Jerónimo Carrión`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 September 1865`,
		leftOffice: `7 November 1867`,
	},
	{
		id: 11015,
		countryId,
		name: `Pedro José de Arteta`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 November 1867`,
		leftOffice: `20 January 1868`,
	},
	{
		id: 11016,
		countryId,
		name: `Javier Espinosa`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `20 January 1868`,
		leftOffice: `19 January 1869`,
	},
	{
		id: 11017,
		countryId,
		name: `Gabriel García Moreno`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `19 January 1869`,
		leftOffice: `19 May 1869`,
	},
	{
		id: 11018,
		countryId,
		name: `Manuel de Ascásubi`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `19 May 1869`,
		leftOffice: `10 August 1869`,
	},
	{
		id: 11019,
		countryId,
		name: `Gabriel García Moreno`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `10 August 1869`,
		leftOffice: `6 August 1875`,
	},
	{
		id: 11020,
		countryId,
		name: `Francisco Xavier León`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `6 August 1875`,
		leftOffice: `15 September 1875`,
	},
	{
		id: 11021,
		countryId,
		name: `José Javier Eguiguren`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `15 September 1875`,
		leftOffice: `9 December 1875`,
	},
	{
		id: 11022,
		countryId,
		name: `Antonio Borrero`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `9 December 1875`,
		leftOffice: `8 September 1876`,
	},
	{
		id: 11023,
		countryId,
		name: `Ignacio de Veintemilla`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `8 September 1876`,
		leftOffice: `10 January 1883`,
	},
	{
		id: 11024,
		countryId,
		name: `Pentevirato Quiteño`,
		party: `Bipartisan`,
		leaning: leanings.CENTRIST,
		tookOffice: `14 January 1883`,
		leftOffice: `15 October 1883`,
	},
	{
		id: 11025,
		countryId,
		name: `Supreme Leadership of Manabí and Esmeraldas`,
		party: `Bipartisan`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 June 1883`,
		leftOffice: `15 October 1883`,
	},
	{
		id: 11026,
		countryId,
		name: `Supreme Leadership of Guayas`,
		party: `Bipartisan`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 July 1883`,
		leftOffice: `15 October 1883`,
	},
	{
		id: 11027,
		countryId,
		name: `José Plácido Caamaño`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `15 October 1883`,
		leftOffice: `1 July 1888`,
	},
	{
		id: 11028,
		countryId,
		name: `Pedro José Cevallos`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 July 1888`,
		leftOffice: `17 August 1888`,
	},
	{
		id: 11029,
		countryId,
		name: `Antonio Flores Jijón`,
		party: `Progressive Party / Republican Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `17 August 1888`,
		leftOffice: `10 June 1892`,
	},
	{
		id: 11030,
		countryId,
		name: `Luis Cordero Crespo`,
		party: `Progressive Party / Republican Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 June 1892`,
		leftOffice: `16 April 1895`,
	},
	{
		id: 11031,
		countryId,
		name: `Vicente Lucio Salazar`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `16 April 1895`,
		leftOffice: `5 June 1895`,
	},
	{
		id: 11032,
		countryId,
		name: `Eloy Alfaro`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 June 1895`,
		leftOffice: `1 September 1901`,
	},
	{
		id: 11033,
		countryId,
		name: `Leónidas Plaza`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 September 1901`,
		leftOffice: `1 September 1905`,
	},
	{
		id: 11034,
		countryId,
		name: `Lizardo García`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 September 1905`,
		leftOffice: `16 January 1906`,
	},
	{
		id: 11035,
		countryId,
		name: `Eloy Alfaro`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 January 1906`,
		leftOffice: `11 August 1911`,
	},
	{
		id: 11036,
		countryId,
		name: `Carlos Freile Zaldumbide`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `11 August 1911`,
		leftOffice: `1 September 1911`,
	},
	{
		id: 11037,
		countryId,
		name: `Emilio Estrada`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 September 1911`,
		leftOffice: `22 December 1911`,
	},
	{
		id: 11038,
		countryId,
		name: `Carlos Freile Zaldumbide`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `22 December 1911`,
		leftOffice: `6 March 1912`,
	},
	{
		id: 11039,
		countryId,
		name: `Francisco Andrade Marín`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `6 March 1912`,
		leftOffice: `1 August 1912`,
	},
	{
		id: 11040,
		countryId,
		name: `Alfredo Baquerizo`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 August 1912`,
		leftOffice: `1 September 1912`,
	},
	{
		id: 11041,
		countryId,
		name: `Leónidas Plaza`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 September 1912`,
		leftOffice: `1 September 1916`,
	},
	{
		id: 11042,
		countryId,
		name: `Alfredo Baquerizo`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 September 1916`,
		leftOffice: `1 September 1920`,
	},
	{
		id: 11043,
		countryId,
		name: `José Luis Tamayo`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 September 1920`,
		leftOffice: `1 September 1924`,
	},
	{
		id: 11044,
		countryId,
		name: `Gonzalo Córdova`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 September 1924`,
		leftOffice: `10 July 1925`,
	},
	{
		id: 11045,
		countryId,
		name: `First Provisional Government`,
		party: `First Provisional Government`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 July 1925`,
		leftOffice: `6 January 1926`,
	},
	{
		id: 11046,
		countryId,
		name: `Second Provisional Government`,
		party: `Second Provisional Government`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 January 1926`,
		leftOffice: `31 March 1926`,
	},
	{
		id: 11047,
		countryId,
		name: `Isidro Ayora`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 April 1926`,
		leftOffice: `24 August 1931`,
	},
	{
		id: 11048,
		countryId,
		name: `Luis Larrea Alba`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `24 August 1931`,
		leftOffice: `15 October 1931`,
	},
	{
		id: 11049,
		countryId,
		name: `Alfredo Baquerizo`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 October 1931`,
		leftOffice: `28 August 1932`,
	},
	{
		id: 11050,
		countryId,
		name: `Carlos Freile Larrea`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `28 August 1932`,
		leftOffice: `2 September 1932`,
	},
	{
		id: 11051,
		countryId,
		name: `Alberto Guerrero Martínez`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 September 1932`,
		leftOffice: `5 December 1932`,
	},
	{
		id: 11052,
		countryId,
		name: `Juan de Dios Martínez`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 December 1932`,
		leftOffice: `20 October 1933`,
	},
	{
		id: 11053,
		countryId,
		name: `Abelardo Montalvo`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 October 1933`,
		leftOffice: `1 September 1934`,
	},
	{
		id: 11054,
		countryId,
		name: `José María Velasco Ibarra`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 September 1934`,
		leftOffice: `21 August 1935`,
	},
	{
		id: 11055,
		countryId,
		name: `Antonio Pons`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `21 August 1935`,
		leftOffice: `26 September 1935`,
	},
	{
		id: 11056,
		countryId,
		name: `Federico Páez Chiriboga`,
		party: `Ecuadorian Socialist Party`,
		leaning: leanings.LEFT,
		tookOffice: `26 September 1935`,
		leftOffice: `23 October 1937`,
	},
	{
		id: 11057,
		countryId,
		name: `Alberto Enríquez Gallo`,
		party: `Ecuadorian Socialist Party`,
		leaning: leanings.LEFT,
		tookOffice: `23 October 1937`,
		leftOffice: `10 August 1938`,
	},
	{
		id: 11058,
		countryId,
		name: `Manuel María Borrero`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 August 1938`,
		leftOffice: `2 December 1938`,
	},
	{
		id: 11059,
		countryId,
		name: `Aurelio Mosquera`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 December 1938`,
		leftOffice: `18 November 1939`,
	},
	{
		id: 11060,
		countryId,
		name: `Carlos Alberto Arroyo del Río`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 November 1939`,
		leftOffice: `11 December 1939`,
	},
	{
		id: 11061,
		countryId,
		name: `Andrés Córdova`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `11 December 1939`,
		leftOffice: `10 August 1940`,
	},
	{
		id: 11062,
		countryId,
		name: `Julio Enrique Moreno`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 August 1940`,
		leftOffice: `1 September 1940`,
	},
	{
		id: 11063,
		countryId,
		name: `Carlos Alberto Arroyo del Río`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 September 1940`,
		leftOffice: `29 May 1944`,
	},
	{
		id: 11064,
		countryId,
		name: `Julio Teodoro Salem`,
		party: `Ecuadorian Radical Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `29 May 1944`,
		leftOffice: `1 June 1944`,
	},
	{
		id: 11065,
		countryId,
		name: `José María Velasco Ibarra`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 June 1944`,
		leftOffice: `23 August 1947`,
	},
	{
		id: 11066,
		countryId,
		name: `Carlos Mancheno Cajas`,
		party: `Ecuadorean Armed Forces`,
		leaning: leanings.CENTRIST,
		tookOffice: `23 August 1947`,
		leftOffice: `2 September 1947`,
	},
	{
		id: 11067,
		countryId,
		name: `Mariano Suárez`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `2 September 1947`,
		leftOffice: `17 September 1947`,
	},
	{
		id: 11068,
		countryId,
		name: `Carlos Julio Arosemena Tola`,
		party: `Independent`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `17 September 1947`,
		leftOffice: `1 September 1948`,
	},
	{
		id: 11069,
		countryId,
		name: `Galo Plaza Lasso`,
		party: `National Democratic Civic Movement`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 September 1948`,
		leftOffice: `1 September 1952`,
	},
	{
		id: 11070,
		countryId,
		name: `José María Velasco Ibarra`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 September 1952`,
		leftOffice: `1 September 1956`,
	},
	{
		id: 11071,
		countryId,
		name: `Camilo Ponce Enríquez`,
		party: `Social Christian Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 September 1956`,
		leftOffice: `1 September 1960`,
	},
	{
		id: 11072,
		countryId,
		name: `José María Velasco Ibarra`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 September 1960`,
		leftOffice: `7 November 1961`,
	},
	{
		id: 11073,
		countryId,
		name: `Carlos Julio Arosemena Monroy`,
		party: `Independent`,
		leaning: leanings.LEFT,
		tookOffice: `7 November 1961`,
		leftOffice: `11 July 1963`,
	},
	{
		id: 11074,
		countryId,
		name: `Military Junta`,
		party: `Ecuadorean Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `11 July 1963`,
		leftOffice: `30 March 1966`,
	},
	{
		id: 11075,
		countryId,
		name: `Clemente Yerovi`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `30 March 1966`,
		leftOffice: `16 November 1966`,
	},
	{
		id: 11076,
		countryId,
		name: `Otto Arosemena`,
		party: `Democratic Institutionalist Coalition`,
		leaning: leanings.RIGHT,
		tookOffice: `16 November 1966`,
		leftOffice: `1 September 1968`,
	},
	{
		id: 11077,
		countryId,
		name: `José María Velasco Ibarra`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 September 1968`,
		leftOffice: `15 February 1972`,
	},
	{
		id: 11078,
		countryId,
		name: `Guillermo Rodríguez`,
		party: `Ecuadorean Armed Forces`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `15 February 1972`,
		leftOffice: `11 January 1976`,
	},
	{
		id: 11079,
		countryId,
		name: `Supreme Government Council`,
		party: `Ecuadorean Armed Forces`,
		leaning: leanings.CENTRIST,
		tookOffice: `11 January 1976`,
		leftOffice: `10 August 1979`,
	},
	{
		id: 11080,
		countryId,
		name: `Jaime Roldós Aguilera`,
		party: `Concentration of People’s Forces`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `10 August 1979`,
		leftOffice: `24 May 1981`,
	},
	{
		id: 11081,
		countryId,
		name: `Osvaldo Hurtado`,
		party: `Popular Democracy`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `24 May 1981`,
		leftOffice: `10 August 1984`,
	},
	{
		id: 11082,
		countryId,
		name: `León Febres-Cordero`,
		party: `Social Christian Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 August 1984`,
		leftOffice: `10 August 1988`,
	},
	{
		id: 11083,
		countryId,
		name: `Rodrigo Borja Cevallos`,
		party: `Party of the Democratic Left`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `10 August 1988`,
		leftOffice: `10 August 1992`,
	},
	{
		id: 11084,
		countryId,
		name: `Sixto Durán-Ballén`,
		party: `Republican Union Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 August 1992`,
		leftOffice: `10 August 1996`,
	},
	{
		id: 11085,
		countryId,
		name: `Abdalá Bucaram`,
		party: `Ecuadorian Roldosist Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 August 1996`,
		leftOffice: `6 February 1997`,
	},
	{
		id: 11086,
		countryId,
		name: `Fabián Alarcón`,
		party: `Alfarista Radical Front`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `6 February 1997`,
		leftOffice: `9 February 1997`,
	},
	{
		id: 11087,
		countryId,
		name: `Rosalía Arteaga`,
		party: `Alfarista Radical Front`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `9 February 1997`,
		leftOffice: `11 February 1997`,
	},
	{
		id: 11088,
		countryId,
		name: `Fabián Alarcón`,
		party: `Alfarista Radical Front`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `11 February 1997`,
		leftOffice: `10 August 1998`,
	},
	{
		id: 11089,
		countryId,
		name: `Jamil Mahuad`,
		party: `Popular Democracy`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 August 1998`,
		leftOffice: `22 January 2000`,
	},
	{
		id: 11090,
		countryId,
		name: `Gustavo Noboa`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `22 January 2000`,
		leftOffice: `January 15 2003`,
	},
	{
		id: 11091,
		countryId,
		name: `Lucio Gutiérrez`,
		party: `Patriotic Society Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 January 2003`,
		leftOffice: `20 April 2005`,
	},
	{
		id: 11092,
		countryId,
		name: `Alfredo Palacio`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 April 2005`,
		leftOffice: `15 January 2007`,
	},
	{
		id: 11093,
		countryId,
		name: `Rafael Correa`,
		party: `PAIS Alliance`,
		leaning: leanings.LEFT,
		tookOffice: `15 January 2007`,
		leftOffice: `24 May 2017`,
	},
	{
		id: 11094,
		countryId,
		name: `Lenín Moreno`,
		party: `PAIS Alliance`,
		leaning: leanings.LEFT,
		tookOffice: `24 May 2017`,
		leftOffice: `24 May 2021`,
	},
	{
		id: 11095,
		countryId,
		name: `Guillermo Lasso`,
		party: `Creating Opportunities`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `24 May 2021`,
		leftOffice: `23 November 2023`,
	},
	{
		id: 11096,
		countryId,
		name: `Daniel Noboa`,
		party: `National Democratic Action`,
		leaning: leanings.RIGHT,
		tookOffice: `23 November 2023`,
		leftOffice: null,
	},
];
