import type { LeaderSeed } from '../../src/data/types';
import { leanings } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/President_of_El_Salvador`;

const countryId = 5;

export const elSalvador: LeaderSeed[] = [
	{
		id: 12000,
		countryId,
		name: `Captaincy General of Guatemala`,
		party: `Kingdom of Spain`,
		leaning: leanings.MONARCHY,
		tookOffice: `1 January 1609`,
		leftOffice: `15 September 1821`,
	},
	{
		id: 12001,
		countryId,
		name: `Gabino Gaínza`,
		party: `Military / Central American Independence`,
		leaning: leanings.MILITARY,
		tookOffice: `15 September 1821`,
		leftOffice: `5 January 1822`,
	},
	{
		id: 12002,
		countryId,
		name: `Agustín de Iturbide`,
		party: `First Mexican Empire`,
		leaning: leanings.MONARCHY,
		tookOffice: `5 January 1822`,
		leftOffice: `1 July 1823`,
	},
	{
		id: 12003,
		countryId,
		name: `Vicente Filísola - Federal Republic of Central America`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 July 1823`,
		leftOffice: `10 July 1823`,
	},
	{
		id: 12004,
		countryId,
		name: `First Triumvirate - Federal Republic of Central America`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 July 1823`,
		leftOffice: `4 October 1823`,
	},
	{
		id: 12005,
		countryId,
		name: `Second Triumvirate - Federal Republic of Central America`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `4 October 1823`,
		leftOffice: `29 April 1825`,
	},
	{
		id: 12006,
		countryId,
		name: `Manuel José Arce - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `29 April 1825`,
		leftOffice: `13 April 1829`,
	},
	{
		id: 12007,
		countryId,
		name: `Mariano Beltranena y Llano - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `13 April 1829`,
		leftOffice: `14 June 1829`,
	},
	{
		id: 12008,
		countryId,
		name: `Francisco Morazán - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `14 June 1829`,
		leftOffice: `25 June 1829`,
	},
	{
		id: 12009,
		countryId,
		name: `José Francisco Barrundia - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `25 June 1829`,
		leftOffice: `16 September 1830`,
	},
	{
		id: 12010,
		countryId,
		name: `Francisco Morazán - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `16 September 1830`,
		leftOffice: `16 September 1834`,
	},
	{
		id: 12011,
		countryId,
		name: `José Gregorio Salazar - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `16 September 1834`,
		leftOffice: `14 February 1835`,
	},
	{
		id: 12012,
		countryId,
		name: `Francisco Morazán - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `14 February 1835`,
		leftOffice: `1 February 1839`,
	},
	{
		id: 12013,
		countryId,
		name: `Diego Vigil y Cocaña - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `1 February 1839`,
		leftOffice: `31 March 1840`,
	},
	// Post Federal Republic of Central America, Pre-Independence
	{
		id: 12014,
		countryId,
		name: `José María Silva`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `31 March 1840`,
		leftOffice: `5 April 1840`,
	},
	{
		id: 12015,
		countryId,
		name: `Municipal Council of San Salvador`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 April 1840`,
		leftOffice: `15 April 1840`,
	},
	{
		id: 12016,
		countryId,
		name: `Antonio José Cañas`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 April 1840`,
		leftOffice: `20 September 1840`,
	},
	{
		id: 12017,
		countryId,
		name: `Norberto Ramírez`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 September 1840`,
		leftOffice: `7 January 1841`,
	},
	{
		id: 12018,
		countryId,
		name: `Juan Lindo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 January 1841`,
		leftOffice: `22 February 1841`,
	},
	// Independence from the Federal Republic of Central America
	{
		id: 12019,
		countryId,
		name: `Juan Lindo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `22 February 1841`,
		leftOffice: `20 June 1841`,
	},
	{
		id: 12020,
		countryId,
		name: `Pedro José Arce`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 June 1841`,
		leftOffice: `28 June 1841`,
	},
	{
		id: 12021,
		countryId,
		name: `Juan Lindo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `28 June 1841`,
		leftOffice: `1 February 1842`,
	},
	{
		id: 12022,
		countryId,
		name: `José Escolástico Marín`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 February 1842`,
		leftOffice: `12 April 1842`,
	},
	{
		id: 12023,
		countryId,
		name: `Juan José Guzmán`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `12 April 1842`,
		leftOffice: `30 June 1842`,
	},
	{
		id: 12024,
		countryId,
		name: `Dionisio Villacorta`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `30 June 1842`,
		leftOffice: `19 July 1842`,
	},
	{
		id: 12025,
		countryId,
		name: `José Escolástico Marín`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `19 July 1842`,
		leftOffice: `26 September 1842`,
	},
	{
		id: 12026,
		countryId,
		name: `Juan José Guzmán`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `26 September 1842`,
		leftOffice: `10 December 1843`,
	},
	{
		id: 12027,
		countryId,
		name: `Cayetano Molina`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 December 1843`,
		leftOffice: `20 December 1843`,
	},
	{
		id: 12028,
		countryId,
		name: `Pedro José Arce`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 December 1843`,
		leftOffice: `29 December 1843`,
	},
	{
		id: 12029,
		countryId,
		name: `Cayetano Molina`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `29 December 1843`,
		leftOffice: `1 January 1844`,
	},
	{
		id: 12030,
		countryId,
		name: `Pedro José Arce`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 January 1844`,
		leftOffice: `1 February 1844`,
	},
	{
		id: 12031,
		countryId,
		name: `Fermín Palacios`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 February 1844`,
		leftOffice: `7 February 1844`,
	},
	{
		id: 12032,
		countryId,
		name: `Francisco Malespín`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 February 1844`,
		leftOffice: `16 February 1845`,
	},
	{
		id: 12033,
		countryId,
		name: `Fermín Palacios`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 February 1845`,
		leftOffice: `25 April 1845`,
	},
	{
		id: 12034,
		countryId,
		name: `Joaquín Eufrasio Guzmán`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `25 April 1845`,
		leftOffice: `1 February 1846`,
	},
	{
		id: 12035,
		countryId,
		name: `Fermín Palacios`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 February 1846`,
		leftOffice: `21 February 1846`,
	},
	{
		id: 12036,
		countryId,
		name: `Eugenio Aguilar`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `21 February 1846`,
		leftOffice: `12 July 1846`,
	},
	{
		id: 12037,
		countryId,
		name: `Fermín Palacios`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 July 1846`,
		leftOffice: `21 July 1846`,
	},
	{
		id: 12038,
		countryId,
		name: `Eugenio Aguilar`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `12 July 1846`,
		leftOffice: `1 February 1848`,
	},
	{
		id: 12039,
		countryId,
		name: `Tomás Medina`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 February 1848`,
		leftOffice: `3 February 1848`,
	},
	{
		id: 12040,
		countryId,
		name: `José Félix Quirós`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 February 1848`,
		leftOffice: `7 February 1848`,
	},
	{
		id: 12041,
		countryId,
		name: `Doroteo Vasconcelos`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `7 February 1848`,
		leftOffice: `26 January 1850`,
	},
	{
		id: 12042,
		countryId,
		name: `Ramón Rodríguez`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `26 January 1850`,
		leftOffice: `1 February 1850`,
	},
	{
		id: 12043,
		countryId,
		name: `Doroteo Vasconcelos`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 February 1850`,
		leftOffice: `12 January 1851`,
	},
	{
		id: 12044,
		countryId,
		name: `Francisco Dueñas`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `12 January 1851`,
		leftOffice: `1 March 1851`,
	},
	{
		id: 12045,
		countryId,
		name: `José Félix Quirós`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1851`,
		leftOffice: `3 May 1851`,
	},
	{
		id: 12046,
		countryId,
		name: `Francisco Dueñas`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `3 May 1851`,
		leftOffice: `30 January 1852`,
	},
	{
		id: 12047,
		countryId,
		name: `José María San Martín`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `30 January 1852`,
		leftOffice: `1 February 1852`,
	},
	{
		id: 12048,
		countryId,
		name: `Francisco Dueñas`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 February 1852`,
		leftOffice: `1 February 1854`,
	},
	{
		id: 12049,
		countryId,
		name: `Vicente Gómez`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 February 1854`,
		leftOffice: `15 February 1854`,
	},
	{
		id: 12050,
		countryId,
		name: `José María San Martín`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `15 February 1854`,
		leftOffice: `1 February 1856`,
	},
	{
		id: 12051,
		countryId,
		name: `Francisco Dueñas`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 February 1856`,
		leftOffice: `12 February 1856`,
	},
	{
		id: 12052,
		countryId,
		name: `Rafael Campo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `12 February 1856`,
		leftOffice: `12 May 1856`,
	},
	{
		id: 12053,
		countryId,
		name: `Francisco Dueñas`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `12 May 1856`,
		leftOffice: `19 July 1856`,
	},
	{
		id: 12054,
		countryId,
		name: `Rafael Campo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `19 July 1856`,
		leftOffice: `1 February 1858`,
	},
	{
		id: 12055,
		countryId,
		name: `Lorenzo Zepeda`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 February 1858`,
		leftOffice: `7 February 1858`,
	},
	{
		id: 12056,
		countryId,
		name: `Miguel Santín del Castillo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 February 1858`,
		leftOffice: `24 June 1858`,
	},
	{
		id: 12057,
		countryId,
		name: `Gerardo Barrios`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `24 June 1858`,
		leftOffice: `18 September 1858`,
	},
	{
		id: 12058,
		countryId,
		name: `Miguel Santín del Castillo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `18 September 1858`,
		leftOffice: `19 January 1859`,
	},
	{
		id: 12059,
		countryId,
		name: `Joaquín Eufrasio Guzmán`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `19 January 1859`,
		leftOffice: `15 February 1859`,
	},
	{
		id: 12060,
		countryId,
		name: `José María Peralta`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 February 1859`,
		leftOffice: `12 March 1859`,
	},
	{
		id: 12061,
		countryId,
		name: `Gerardo Barrios`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `12 March 1859`,
		leftOffice: `1 February 1860`,
	},
	{
		id: 12062,
		countryId,
		name: `Gerardo Barrios`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 February 1860`,
		leftOffice: `16 December 1860`,
	},
	{
		id: 12063,
		countryId,
		name: `José María Peralta`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 December 1860`,
		leftOffice: `7 February 1861`,
	},
	{
		id: 12064,
		countryId,
		name: `Gerardo Barrios`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `7 February 1861`,
		leftOffice: `26 October 1863`,
	},
	{
		id: 12065,
		countryId,
		name: `Francisco Dueñas`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `26 October 1863`,
		leftOffice: `1 February 1865`,
	},
	{
		id: 12066,
		countryId,
		name: `Francisco Dueñas`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 February 1865`,
		leftOffice: `12 April 1871`,
	},
	{
		id: 12067,
		countryId,
		name: `Santiago González Portillo`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `12 April 1871`,
		leftOffice: `1 February 1872`,
	},
	{
		id: 12068,
		countryId,
		name: `Santiago González Portillo`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 February 1872`,
		leftOffice: `10 May 1872`,
	},
	{
		id: 12069,
		countryId,
		name: `Manuel Méndez`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 May 1872`,
		leftOffice: `16 June 1872`,
	},
	{
		id: 12070,
		countryId,
		name: `Santiago González Portillo`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `16 June 1872`,
		leftOffice: `1 February 1876`,
	},
	{
		id: 12071,
		countryId,
		name: `Andrés del Valle`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 February 1876`,
		leftOffice: `1 May 1876`,
	},
	{
		id: 12072,
		countryId,
		name: `Rafael Zaldívar`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 May 1876`,
		leftOffice: `1 February 1880`,
	},
	{
		id: 12073,
		countryId,
		name: `Andrés del Valle`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 February 1876`,
		leftOffice: `1 May 1876`,
	},
	{
		id: 12074,
		countryId,
		name: `Rafael Zaldívar`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 May 1876`,
		leftOffice: `21 June 1885`,
	},
	{
		id: 12075,
		countryId,
		name: `Francisco Menéndez`,
		party: `Armed Forces of El Salvador - Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `21 June 1885`,
		leftOffice: `22 June 1890`,
	},
	{
		id: 12076,
		countryId,
		name: `Carlos Basilio Ezeta y León`,
		party: `Armed Forces of El Salvador - Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `22 June 1890`,
		leftOffice: `10 June 1894`,
	},
	{
		id: 12077,
		countryId,
		name: `Rafael Antonio Gutiérrez`,
		party: `Armed Forces of El Salvador - Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `10 June 1894`,
		leftOffice: `14 November 1898`,
	},
	{
		id: 12078,
		countryId,
		name: `Tomás Regalado`,
		party: `Armed Forces of El Salvador - Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `14 November 1898`,
		leftOffice: `1 March 1903`,
	},
	{
		id: 12079,
		countryId,
		name: `Pedro José Escalón`,
		party: `Armed Forces of El Salvador - Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 March 1903`,
		leftOffice: `1 March 1907`,
	},
	{
		id: 12080,
		countryId,
		name: `Fernando Figueroa`,
		party: `Armed Forces of El Salvador - Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 March 1907`,
		leftOffice: `1 March 1911`,
	},
	{
		id: 12081,
		countryId,
		name: `Manuel Enrique Araujo`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1911`,
		leftOffice: `8 February 1913`,
	},
	{
		id: 12082,
		countryId,
		name: `Carlos Meléndez`,
		party: `National Democratic Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `8 February 1913`,
		leftOffice: `29 August 1914`,
	},
	{
		id: 12083,
		countryId,
		name: `Alfonso Quiñónez Molina`,
		party: `National Democratic Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `29 August 1914`,
		leftOffice: `1 March 1915`,
	},
	{
		id: 12084,
		countryId,
		name: `Carlos Meléndez`,
		party: `National Democratic Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1915`,
		leftOffice: `21 December 1918`,
	},
	{
		id: 12085,
		countryId,
		name: `Alfonso Quiñónez Molina`,
		party: `National Democratic Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `21 December 1918`,
		leftOffice: `1 March 1919`,
	},
	{
		id: 12086,
		countryId,
		name: `Jorge Meléndez`,
		party: `National Democratic Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1919`,
		leftOffice: `1 March 1923`,
	},
	{
		id: 12087,
		countryId,
		name: `Alfonso Quiñónez Molina`,
		party: `National Democratic Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1923`,
		leftOffice: `1 March 1927`,
	},
	{
		id: 12088,
		countryId,
		name: `Pío Romero Bosque`,
		party: `National Democratic Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1927`,
		leftOffice: `1 March 1931`,
	},
	{
		id: 12089,
		countryId,
		name: `Arturo Araujo`,
		party: `Labor Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 March 1931`,
		leftOffice: `2 December 1931`,
	},
	{
		id: 12090,
		countryId,
		name: `Maximiliano Hernández Martínez`,
		party: `National Pro Patria Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `4 December 1931`,
		leftOffice: `29 August 1934`,
	},
	{
		id: 12091,
		countryId,
		name: `Andrés Ignacio Menéndez`,
		party: `Armed Forces of El Salvador/National Pro-Patria Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `29 August 1934`,
		leftOffice: `1 March 1935`,
	},
	{
		id: 12092,
		countryId,
		name: `Maximiliano Hernández Martínez`,
		party: `National Pro Patria Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 March 1935`,
		leftOffice: `9 May 1944`,
	},
	{
		id: 12093,
		countryId,
		name: `Andrés Ignacio Menéndez`,
		party: `Armed Forces of El Salvador / National Pro-Patria Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `9 May 1944`,
		leftOffice: `21 October 1944`,
	},
	{
		id: 12094,
		countryId,
		name: `Osmín Aguirre y Salinas`,
		party: `Armed Forces of El Salvador`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `21 October 1944`,
		leftOffice: `1 March 1945`,
	},
	{
		id: 12095,
		countryId,
		name: `Salvador Castaneda Castro`,
		party: `Armed Forces of El Salvador / Unification Social Democratic Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 March 1945`,
		leftOffice: `15 December 1948`,
	},
	{
		id: 12096,
		countryId,
		name: `Revolutionary Council of Government`,
		party: `Revolutionary Council of Government`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 December 1948`,
		leftOffice: `14 September 1950`,
	},
	{
		id: 12097,
		countryId,
		name: `Óscar Osorio`,
		party: `Armed Forces of El Salvador / Revolutionary Party of Democratic Unification`,
		leaning: leanings.RIGHT,
		tookOffice: `14 September 1950`,
		leftOffice: `14 September 1956`,
	},
	{
		id: 12098,
		countryId,
		name: `José María Lemus`,
		party: `Armed Forces of El Salvador / Revolutionary Party of Democratic Unification`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `14 September 1956`,
		leftOffice: `26 October 1960`,
	},
	{
		id: 12099,
		countryId,
		name: `Junta of Government`,
		party: `Junta of Government`,
		leaning: 0,
		tookOffice: `26 October 1960`,
		leftOffice: `25 January 1961`,
	},
	{
		id: 12100,
		countryId,
		name: `Civic-Military Directory`,
		party: `Civic-Military Directory`,
		leaning: 0,
		tookOffice: `25 January 1961`,
		leftOffice: `25 January 1962`,
	},
	{
		id: 12101,
		countryId,
		name: `Eusebio Rodolfo Cordón Cea`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 January 1962`,
		leftOffice: `1 July 1962`,
	},
	{
		id: 12102,
		countryId,
		name: `Julio Adalberto Rivera`,
		party: `National Coalition Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 July 1962`,
		leftOffice: `1 July 1967`,
	},
	{
		id: 12103,
		countryId,
		name: `Fidel Sánchez Hernández`,
		party: `National Coalition Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 July 1967`,
		leftOffice: `1 July 1972`,
	},
	{
		id: 12104,
		countryId,
		name: `Arturo Armando Molina`,
		party: `Armed Forces of El Salvador / Party of National Conciliation`,
		leaning: leanings.RIGHT,
		tookOffice: `1 July 1972`,
		leftOffice: `1 July 1977`,
	},
	{
		id: 12105,
		countryId,
		name: `Carlos Humberto Romero`,
		party: `Armed Forces of El Salvador / Party of National Conciliation`,
		leaning: leanings.RIGHT,
		tookOffice: `1 July 1977`,
		leftOffice: `15 October 1979`,
	},
	{
		id: 12106,
		countryId,
		name: `Revolutionary Government Junta`,
		party: `Armed Forces of El Salvador`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `15 October 1979`,
		leftOffice: `2 May 1982`,
	},
	{
		id: 12107,
		countryId,
		name: `Álvaro Magaña`,
		party: `Nationalist Republican Alliance`,
		leaning: leanings.RIGHT,
		tookOffice: `2 May 1982`,
		leftOffice: `1 June 1984`,
	},
	{
		id: 12108,
		countryId,
		name: `José Napoleón Duarte`,
		party: `Christian Democratic Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 June 1984`,
		leftOffice: `1 June 1989`,
	},
	{
		id: 12109,
		countryId,
		name: `Alfredo Cristiani`,
		party: `Nationalist Republican Alliance`,
		leaning: leanings.RIGHT,
		tookOffice: `1 June 1989`,
		leftOffice: `1 June 1994`,
	},
	{
		id: 12110,
		countryId,
		name: `Armando Calderón Sol`,
		party: `Nationalist Republican Alliance`,
		leaning: leanings.RIGHT,
		tookOffice: `1 June 1994`,
		leftOffice: `1 June 1999`,
	},
	{
		id: 12111,
		countryId,
		name: `Francisco Flores Pérez`,
		party: `Nationalist Republican Alliance`,
		leaning: leanings.RIGHT,
		tookOffice: `1 June 1999`,
		leftOffice: `1 June 2004`,
	},
	{
		id: 12112,
		countryId,
		name: `Antonio Saca`,
		party: `Nationalist Republican Alliance`,
		leaning: leanings.RIGHT,
		tookOffice: `1 June 2004`,
		leftOffice: `1 June 2009`,
	},
	{
		id: 12113,
		countryId,
		name: `Mauricio Funes`,
		party: `Farabundo Martí National Liberation Front`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `1 June 2009`,
		leftOffice: `1 June 2014`,
	},
	{
		id: 12114,
		countryId,
		name: `Salvador Sánchez Cerén`,
		party: `Farabundo Martí National Liberation Front`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `1 June 2014`,
		leftOffice: `1 June 2019`,
	},
	{
		id: 12115,
		countryId,
		name: `Nayib Armando Bukele Ortez`,
		party: `Nuevas Ideas`,
		leaning: leanings.RIGHT,
		tookOffice: `1 June 2019`,
		leftOffice: null,
	},
];
