import type { LeaderSeed } from '../../src/data/types';
import { leanings } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_heads_of_state_of_Guyana`;

const countryId = 13;

export const guyana: LeaderSeed[] = [
	{
		id: 14000,
		countryId,
		name: `Elizabeth II`,
		party: `British Monarchy`,
		leaning: leanings.MONARCHY,
		tookOffice: `26 May 1966`,
		leftOffice: `17 March 1970`,
	},
	{
		id: 14001,
		countryId,
		name: `Arthur Chung`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `17 March 1970`,
		leftOffice: `6 October 1980`,
	},
	{
		id: 14002,
		countryId,
		name: `Forbes Burnham`,
		party: `People's National Congress Reform`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `6 October 1980`,
		leftOffice: `6 August 1985`,
	},
	{
		id: 14003,
		countryId,
		name: `Desmond Hoyte`,
		party: `People's National Congress Reform`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `6 August 1985`,
		leftOffice: `9 October 1992`,
	},
	{
		id: 14004,
		countryId,
		name: `Cheddi Jagan`,
		party: `People's Progressive Party`,
		leaning: leanings.LEFT,
		tookOffice: `9 October 1992`,
		leftOffice: `6 March 1997`,
	},
	{
		id: 14005,
		countryId,
		name: `Sam Hinds`,
		party: `People's Progressive Party`,
		leaning: leanings.LEFT,
		tookOffice: `6 March 1997`,
		leftOffice: `19 December 1997`,
	},
	{
		id: 14006,
		countryId,
		name: `Janet Jagan`,
		party: `People's Progressive Party`,
		leaning: leanings.LEFT,
		tookOffice: `19 December 1997`,
		leftOffice: `11 August 1999`,
	},
	{
		id: 14007,
		countryId,
		name: `Bharrat Jagdeo`,
		party: `People's Progressive Party`,
		leaning: leanings.LEFT,
		tookOffice: `11 August 1999`,
		leftOffice: `3 December 2011`,
	},
	{
		id: 14008,
		countryId,
		name: `Donald Ramotar`,
		party: `People's Progressive Party`,
		leaning: leanings.LEFT,
		tookOffice: `3 December 2011`,
		leftOffice: `16 May 2015`,
	},
	{
		id: 14009,
		countryId,
		name: `David Granger`,
		party: `People's National Congress Reform`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `16 May 2015`,
		leftOffice: `2 August 2020`,
	},
	{
		id: 14010,
		countryId,
		name: `Irfaan Ali`,
		party: `People's Progressive Party`,
		leaning: leanings.LEFT,
		tookOffice: `2 August 2020`,
		leftOffice: null,
	},
];
