import type { LeaderSeed } from '../../src/data/types';
import { leanings } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_heads_of_state_of_Haiti`;

const countryId = 26;

export const haiti: LeaderSeed[] = [
	{
		id: 15000,
		countryId,
		name: `French Saint-Domingue`,
		party: `French Empire`,
		leaning: leanings.MONARCHY,
		tookOffice: `1 January 1625`,
		leftOffice: `1 January 1791`,
	},
	{
		id: 15001,
		countryId,
		name: `Toussaint Louverture`,
		party: `Independent / Military`,
		leaning: leanings.MILITARY,
		tookOffice: `1 January 1791`,
		leftOffice: `6 May 1802`,
	},
	{
		id: 15002,
		countryId,
		name: `Vacant Presidency`,
		party: `French Invasion - Total War`,
		leaning: leanings.MILITARY,
		tookOffice: `6 May 1802`,
		leftOffice: `1 January 1804`,
	},
	{
		id: 15003,
		countryId,
		name: `Jean-Jacques Dessalines`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 January 1804`,
		leftOffice: `22 September 1804`,
	},
	{
		id: 15004,
		countryId,
		name: `Jacques I`,
		party: `First Empire of Haiti`,
		leaning: leanings.MONARCHY,
		tookOffice: `22 September 1804`,
		leftOffice: `17 October 1806`,
	},
	{
		id: 15005,
		countryId,
		name: `Henri Christophe`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `17 October 1806`,
		leftOffice: `28 March 1811`,
	},
	{
		id: 15006,
		countryId,
		name: `Henry I`,
		party: `Kingdom of Haiti`,
		leaning: leanings.MONARCHY,
		tookOffice: `28 March 1811`,
		leftOffice: `18 October 1820`,
	},
	{
		id: 15007,
		countryId,
		name: `Jean-Pierre Boyer`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 October 1820`,
		leftOffice: `13 February 1843`,
	},
	{
		id: 15008,
		countryId,
		name: `Charles Rivière-Hérard`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `4 April 1843`,
		leftOffice: `3 May 1844`,
	},
	{
		id: 15009,
		countryId,
		name: `Philippe Guerrier`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 May 1844`,
		leftOffice: `16 April 1845`,
	},
	{
		id: 15010,
		countryId,
		name: `Jean-Louis Pierrot`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 April 1845`,
		leftOffice: `24 March 1846`,
	},
	{
		id: 15011,
		countryId,
		name: `Jean-Baptiste Riché`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `24 March 1846`,
		leftOffice: `2 March 1847`,
	},
	{
		id: 15012,
		countryId,
		name: `Faustin Soulouque`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 March 1847`,
		leftOffice: `26 August 1849`,
	},
	{
		id: 15013,
		countryId,
		name: `Faustin I`,
		party: `Second Empire of Haiti`,
		leaning: leanings.MONARCHY,
		tookOffice: `26 August 1849`,
		leftOffice: `22 January 1859`,
	},
	{
		id: 15014,
		countryId,
		name: `Fabre Geffrard`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `22 January 1859`,
		leftOffice: `20 March 1867`,
	},
	{
		id: 15015,
		countryId,
		name: `Jean-Nicolas Nissage Saget`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 March 1867`,
		leftOffice: `4 May 1867`,
	},
	{
		id: 15016,
		countryId,
		name: `Sylvain Salnave`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `4 May 1867`,
		leftOffice: `27 December 1869`,
	},
	{
		id: 15017,
		countryId,
		name: `Jean-Nicolas Nissage Saget`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `27 December 1869`,
		leftOffice: `14 May 1874`,
	},
	{
		id: 15018,
		countryId,
		name: `Council of Secretaries of State`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `14 May 1874`,
		leftOffice: `14 June 1874`,
	},
	{
		id: 15019,
		countryId,
		name: `Michel Domingue`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `14 June 1874`,
		leftOffice: `23 April 1876`,
	},
	{
		id: 15020,
		countryId,
		name: `Pierre Théoma Boisrond-Canal`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `23 April 1876`,
		leftOffice: `26 July 1879`,
	},
	{
		id: 15021,
		countryId,
		name: `Joseph Lamothe`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `26 July 1879`,
		leftOffice: `2 October 1879`,
	},
	{
		id: 15022,
		countryId,
		name: `Lysius Salomon`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 October 1879`,
		leftOffice: `10 August 1888`,
	},
	{
		id: 15023,
		countryId,
		name: `Pierre Théoma Boisrond-Canal`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `10 August 1888`,
		leftOffice: `16 October 1888`,
	},
	{
		id: 15024,
		countryId,
		name: `François Denys Légitime`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `16 October 1888`,
		leftOffice: `23 August 1889`,
	},
	{
		id: 15025,
		countryId,
		name: `Monpoint Jeune`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `23 August 1889`,
		leftOffice: `17 October 1889`,
	},
	{
		id: 15026,
		countryId,
		name: `Florvil Hyppolite`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `17 October 1889`,
		leftOffice: `31 March 1896`,
	},
	{
		id: 15027,
		countryId,
		name: `Tirésias Simon Sam`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `31 March 1896`,
		leftOffice: `12 May 1902`,
	},
	{
		id: 15028,
		countryId,
		name: `Pierre Théoma Boisrond-Canal`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `12 May 1902`,
		leftOffice: `21 December 1902`,
	},
	{
		id: 15029,
		countryId,
		name: `Pierre Nord Alexis`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `21 December 1902`,
		leftOffice: `6 December 1908`,
	},
	{
		id: 15030,
		countryId,
		name: `François C. Antoine Simon`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `6 December 1908`,
		leftOffice: `15 August 1911`,
	},
	{
		id: 15031,
		countryId,
		name: `Cincinnatus Leconte`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 August 1911`,
		leftOffice: `8 August 1912`,
	},
	{
		id: 15032,
		countryId,
		name: `Tancrède Auguste`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `8 August 1912`,
		leftOffice: `12 May 1913`,
	},
	{
		id: 15033,
		countryId,
		name: `Michel Oreste`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 May 1913`,
		leftOffice: `8 February 1914`,
	},
	{
		id: 15034,
		countryId,
		name: `Oreste Zamor`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `8 February 1914`,
		leftOffice: `7 November 1914`,
	},
	{
		id: 15035,
		countryId,
		name: `Joseph Davilmar Théodore`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `7 November 1914`,
		leftOffice: `25 February 1915`,
	},
	{
		id: 15036,
		countryId,
		name: `Vilbrun Guillaume Sam`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `25 February 1915`,
		leftOffice: `12 August 1915`,
	},
	{
		id: 15037,
		countryId,
		name: `Philippe Sudré Dartiguenave`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 August 1915`,
		leftOffice: `15 May 1922`,
	},
	{
		id: 15038,
		countryId,
		name: `Louis Borno`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 May 1922`,
		leftOffice: `15 May 1930`,
	},
	{
		id: 15039,
		countryId,
		name: `Louis Eugène Roy`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 May 1930`,
		leftOffice: `18 November 1930`,
	},
	{
		id: 15040,
		countryId,
		name: `Sténio Vincent`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 November 1930`,
		leftOffice: `15 May 1941`,
	},
	{
		id: 15041,
		countryId,
		name: `Élie Lescot`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `15 May 1941`,
		leftOffice: `11 January 1946`,
	},
	{
		id: 15042,
		countryId,
		name: `Franck Lavaud`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `11 January 1946`,
		leftOffice: `16 August 1946`,
	},
	{
		id: 15043,
		countryId,
		name: `Dumarsais Estimé`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 August 1946`,
		leftOffice: `10 May 1950`,
	},
	{
		id: 15044,
		countryId,
		name: `Franck Lavaud`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `10 May 1950`,
		leftOffice: `6 December 1950`,
	},
	{
		id: 15045,
		countryId,
		name: `Paul Magloire`,
		party: `Peasant Worker Movement`,
		leaning: leanings.CENTRIST,
		tookOffice: `6 December 1950`,
		leftOffice: `12 December 1956`,
	},
	{
		id: 15046,
		countryId,
		name: `Joseph Nemours Pierre-Louis`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 December 1956`,
		leftOffice: `7 February 1957`,
	},
	{
		id: 15047,
		countryId,
		name: `Franck Sylvain`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 February 1957`,
		leftOffice: `2 April 1957`,
	},
	{
		id: 15048,
		countryId,
		name: `Executive Government Council`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 April 1957`,
		leftOffice: `25 May 1957`,
	},
	{
		id: 15049,
		countryId,
		name: `Daniel Fignolé`,
		party: `Peasant Worker Movement`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 May 1957`,
		leftOffice: `14 June 1957`,
	},
	{
		id: 15050,
		countryId,
		name: `Antonio Thrasybule Kébreau`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `14 June 1957`,
		leftOffice: `22 October 1957`,
	},
	{
		id: 15051,
		countryId,
		name: `François Duvalier`,
		party: `National Unity Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `22 October 1957`,
		leftOffice: `21 April 1971`,
	},
	{
		id: 15052,
		countryId,
		name: `Jean-Claude Duvalier`,
		party: `National Unity Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `21 April 1971`,
		leftOffice: `7 February 1986`,
	},
	{
		id: 15053,
		countryId,
		name: `Henri Namphy`,
		party: `Armed Forces of Haiti`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 February 1986`,
		leftOffice: `7 February 1988`,
	},
	{
		id: 15054,
		countryId,
		name: `Leslie Manigat`,
		party: `Rally of Progressive National Democrats`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `7 February 1988`,
		leftOffice: `20 June 1988`,
	},
	{
		id: 15055,
		countryId,
		name: `Henri Namphy`,
		party: `Armed Forces of Haiti`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 June 1988`,
		leftOffice: `17 September 1988`,
	},
	{
		id: 15056,
		countryId,
		name: `Prosper Avril`,
		party: `Armed Forces of Haiti`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `17 September 1988`,
		leftOffice: `10 March 1990`,
	},
	{
		id: 15057,
		countryId,
		name: `Hérard Abraham`,
		party: `Armed Forces of Haiti`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 March 1990`,
		leftOffice: `13 March 1990`,
	},
	{
		id: 15058,
		countryId,
		name: `Ertha Pascal-Trouillot`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `13 March 1990`,
		leftOffice: `7 February 1991`,
	},
	{
		id: 15059,
		countryId,
		name: `Jean-Bertrand Aristide`,
		party: `Struggling People's Organization`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `7 February 1991`,
		leftOffice: `29 September 1991`,
	},
	{
		id: 15060,
		countryId,
		name: `Raoul Cédras`,
		party: `Armed Forces of Haiti`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `29 September 1991`,
		leftOffice: `8 October 1991`,
	},
	{
		id: 15061,
		countryId,
		name: `Joseph Nérette`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `8 October 1991`,
		leftOffice: `19 June 1992`,
	},
	{
		id: 15062,
		countryId,
		name: `Council of Ministers & Prime Minister Marc Bazin`,
		party: `Movement for the Instauration of Democracy in Haiti`,
		leaning: leanings.RIGHT,
		tookOffice: `19 June 1992`,
		leftOffice: `15 June 1993`,
	},
	{
		id: 15063,
		countryId,
		name: `Jean-Bertrand Aristide`,
		party: `Struggling People's Organization`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `15 June 1993`,
		leftOffice: `12 May 1994`,
	},
	{
		id: 15064,
		countryId,
		name: `Émile Jonassaint`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 May 1994`,
		leftOffice: `12 October 1994`,
	},
	{
		id: 15065,
		countryId,
		name: `Jean-Bertrand Aristide`,
		party: `Struggling People's Organization`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `12 October 1994`,
		leftOffice: `7 February 1996`,
	},
	{
		id: 15066,
		countryId,
		name: `René Préval`,
		party: `Lavalas Family`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `7 February 1996`,
		leftOffice: `7 February 2001`,
	},
	{
		id: 15067,
		countryId,
		name: `Jean-Bertrand Aristide`,
		party: `Lavalas Family`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `7 February 2001`,
		leftOffice: `29 February 2004`,
	},
	{
		id: 15068,
		countryId,
		name: `Boniface Alexandre`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `29 February 2004`,
		leftOffice: `14 May 2006`,
	},
	{
		id: 15069,
		countryId,
		name: `René Préval`,
		party: `Lespwa / Inite`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `14 May 2006`,
		leftOffice: `14 May 2011`,
	},
	{
		id: 15070,
		countryId,
		name: `Michel Martelly`,
		party: `Repons Peyizan`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `14 May 2011`,
		leftOffice: `7 February 2016`,
	},
	{
		id: 15071,
		countryId,
		name: `Council of Ministers & Prime Minister Evans Paul`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 February 2016`,
		leftOffice: `14 February 2016`,
	},
	{
		id: 15072,
		countryId,
		name: `Jocelerme Privert`,
		party: `Inite`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `14 February 2016`,
		leftOffice: `7 February 2017`,
	},
	{
		id: 15073,
		countryId,
		name: `Jovenel Moïse`,
		party: `Haitian Tèt Kale Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `7 February 2017`,
		leftOffice: `7 July 2021`,
	},
	{
		id: 15074,
		countryId,
		name: `Council of Ministers - Claude Joseph`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 July 2021`,
		leftOffice: `20 July 2021`,
	},
	{
		id: 15075,
		countryId,
		name: `Council of Ministers - Ariel Henry`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 July 2021`,
		leftOffice: `24 April 2024`,
	},
	{
		id: 15076,
		countryId,
		name: `Transitional Presidential Council - Edgard Leblanc Fils`,
		party: `Struggling People's Organization`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `24 April 2024`,
		leftOffice: `7 October 2024`,
	},
	{
		id: 15077,
		countryId,
		name: `Transitional Presidential Council - Leslie Voltaire`,
		party: `Fanmi Lavalas`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `7 October 2024`,
		leftOffice: null,
	}
];
