import type { LeaderSeed } from '../../src/data/types';
import { leanings } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_heads_of_state_of_Mexico`;

const countryId = 2;

export const mexico: LeaderSeed[] = [
	{
		id: 18000,
		countryId,
		name: `Viceroyalty of New Spain`,
		party: `Kingdom of Spain`,
		leaning: leanings.MONARCHY,
		tookOffice: `18 August 1521`,
		leftOffice: `28 September 1821`,
	},
	{
		id: 18001,
		countryId,
		name: `First Regency`,
		party: `First Mexican Empire`,
		leaning: leanings.MONARCHY,
		tookOffice: `28 September 1821`,
		leftOffice: `11 April 1822`,
	},
	{
		id: 18002,
		countryId,
		name: `Second Regency`,
		party: `Second Mexican Empire`,
		leaning: leanings.MONARCHY,
		tookOffice: `11 April 1822`,
		leftOffice: `19 May 1822`,
	},
	{
		id: 18003,
		countryId,
		name: `Agustín I`,
		party: `Royal House of Agustín de Iturbide I`,
		leaning: leanings.MONARCHY,
		tookOffice: `19 May 1822`,
		leftOffice: `1 April 1823`,
	},
	{
		id: 18004,
		countryId,
		name: `Provisional Government of Mexico`,
		party: `Provisional Government of Mexico`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 April 1823`,
		leftOffice: `10 October 1824`,
	},
	{
		id: 18005,
		countryId,
		name: `Guadalupe Victoria`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 October 1824`,
		leftOffice: `1 April 1829`,
	},
	{
		id: 18006,
		countryId,
		name: `Vicente Guerrero`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 April 1829`,
		leftOffice: `17 December 1829`,
	},
	{
		id: 18007,
		countryId,
		name: `José María Bocanegra`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `17 December 1829`,
		leftOffice: `23 December 1829`,
	},
	{
		id: 18008,
		countryId,
		name: `Vélez -Quintanar-Alaman`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `23 December 1829`,
		leftOffice: `1 January 1830`,
	},
	{
		id: 18009,
		countryId,
		name: `Anastasio Bustamante`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 January 1830`,
		leftOffice: `14 August 1832`,
	},
	{
		id: 18010,
		countryId,
		name: `Melchor Múzquiz`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `14 August 1832`,
		leftOffice: `24 December 1832`,
	},
	{
		id: 18011,
		countryId,
		name: `Manuel Gómez Pedraza`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `24 December 1832`,
		leftOffice: `1 April 1833`,
	},
	{
		id: 18012,
		countryId,
		name: `Valentín Gómez Farías`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 April 1833`,
		leftOffice: `16 May 1833`,
	},
	{
		id: 18013,
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `16 May 1833`,
		leftOffice: `3 June 1833`,
	},
	{
		id: 18014,
		countryId,
		name: `Valentín Gómez Farías`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `3 June 1833`,
		leftOffice: `18 June 1833`,
	},
	{
		id: 18015,
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `18 June 1833`,
		leftOffice: `5 July 1833`,
	},
	{
		id: 18016,
		countryId,
		name: `Valentín Gómez Farías`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `5 July 1833`,
		leftOffice: `27 October 1833`,
	},
	{
		id: 18017,
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `27 October 1833`,
		leftOffice: `16 December 1833`,
	},
	{
		id: 18018,
		countryId,
		name: `Valentín Gómez Farías`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `16 December 1833`,
		leftOffice: `24 April 1834`,
	},
	{
		id: 18019,
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `24 April 1834`,
		leftOffice: `27 January 1835`,
	},
	{
		id: 18020,
		countryId,
		name: `Miguel Barragán`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `27 January 1835`,
		leftOffice: `27 February 1836`,
	},
	{
		id: 18021,
		countryId,
		name: `José Justo Corro`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `27 February 1836`,
		leftOffice: `19 April 1837`,
	},
	{
		id: 18022,
		countryId,
		name: `Anastasio Bustamante`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `19 April 1837`,
		leftOffice: `18 March 1839`,
	},
	{
		id: 18023,
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `18 March 1839`,
		leftOffice: `11 July 1839`,
	},
	{
		id: 18024,
		countryId,
		name: `Nicolás Bravo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `11 July 1839`,
		leftOffice: `19 July 1839`,
	},
	{
		id: 18025,
		countryId,
		name: `Anastasio Bustamante`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `19 July 1839`,
		leftOffice: `22 September 1841`,
	},
	{
		id: 18026,
		countryId,
		name: `Francisco Javier Echeverría`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `22 September 1841`,
		leftOffice: `10 October 1841`,
	},
	{
		id: 18027,
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `10 October 1841`,
		leftOffice: `26 October 1842`,
	},
	{
		id: 18028,
		countryId,
		name: `Nicolás Bravo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `26 October 1842`,
		leftOffice: `4 March 1843`,
	},
	{
		id: 18029,
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `4 March 1843`,
		leftOffice: `4 October 1843`,
	},
	{
		id: 18030,
		countryId,
		name: `Valentín Canalizo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `4 October 1843`,
		leftOffice: `4 June 1844`,
	},
	{
		id: 18031,
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `4 June 1844`,
		leftOffice: `12 September 1844`,
	},
	{
		id: 18032,
		countryId,
		name: `José Joaquín de Herrera`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `12 September 1844`,
		leftOffice: `21 September 1844`,
	},
	{
		id: 18033,
		countryId,
		name: `Valentín Canalizo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `21 September 1844`,
		leftOffice: `6 December 1844`,
	},
	{
		id: 18034,
		countryId,
		name: `José Joaquín de Herrera`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `6 December 1844`,
		leftOffice: `31 December 1845`,
	},
	{
		id: 18035,
		countryId,
		name: `Mariano Paredes`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `31 December 1845`,
		leftOffice: `28 July 1846`,
	},
	{
		id: 18036,
		countryId,
		name: `Nicolás Bravo`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `28 July 1846`,
		leftOffice: `5 August 1846`,
	},
	{
		id: 18037,
		countryId,
		name: `José Mariano Salas`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `5 August 1846`,
		leftOffice: `23 December 1846`,
	},
	{
		id: 18038,
		countryId,
		name: `Valentín Gómez Farías`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `23 December 1846`,
		leftOffice: `21 March 1847`,
	},
	{
		id: 18039,
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `21 March 1847`,
		leftOffice: `2 April 1847`,
	},
	{
		id: 18040,
		countryId,
		name: `Pedro María de Anaya`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `2 April 1847`,
		leftOffice: `20 May 1847`,
	},
	{
		id: 18041,
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `20 May 1847`,
		leftOffice: `16 September 1847`,
	},
	{
		id: 18042,
		countryId,
		name: `Manuel de la Peña y Peña`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `16 September 1847`,
		leftOffice: `13 November 1847`,
	},
	{
		id: 18043,
		countryId,
		name: `Pedro María de Anaya`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `13 November 1847`,
		leftOffice: `8 January 1848`,
	},
	{
		id: 18044,
		countryId,
		name: `Manuel de la Peña y Peña`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `8 January 1848`,
		leftOffice: `3 June 1848`,
	},
	{
		id: 18045,
		countryId,
		name: `José Joaquín de Herrera`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `3 June 1848`,
		leftOffice: `15 January 1851`,
	},
	{
		id: 18046,
		countryId,
		name: `Mariano Arista`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `15 January 1851`,
		leftOffice: `6 January 1853`,
	},
	{
		id: 18047,
		countryId,
		name: `Juan Bautista Ceballos`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `6 January 1853`,
		leftOffice: `8 February 1853`,
	},
	{
		id: 18048,
		countryId,
		name: `Manuel María Lombardini`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `8 February 1853`,
		leftOffice: `20 April 1853`,
	},
	{
		id: 18049,
		countryId,
		name: `Antonio López de Santa Anna`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `20 April 1853`,
		leftOffice: `5 August 1855`,
	},
	{
		id: 18050,
		countryId,
		name: `Martín Carrera`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `5 August 1855`,
		leftOffice: `12 September 1855`,
	},
	{
		id: 18051,
		countryId,
		name: `Rómulo Díaz de la Vega`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `12 September 1855`,
		leftOffice: `4 October 1855`,
	},
	{
		id: 18052,
		countryId,
		name: `Juan Álvarez`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `4 October 1855`,
		leftOffice: `11 December 1855`,
	},
	{
		id: 18053,
		countryId,
		name: `Ignacio Comonfort`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `11 December 1855`,
		leftOffice: `17 December 1857`,
	},
	{
		id: 18054,
		countryId,
		name: `Ignacio Comonfort`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `17 December 1857`,
		leftOffice: `21 January 1858`,
	},
	{
		id: 18055,
		countryId,
		name: `Félix María Zuloaga`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `11 January 1858`,
		leftOffice: `24 December 1858`,
	},
	{
		id: 18056,
		countryId,
		name: `Manuel Robles Pezuela`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `24 December 1858`,
		leftOffice: `24 January 1859`,
	},
	{
		id: 18057,
		countryId,
		name: `Félix María Zuloaga`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `24 January 1859`,
		leftOffice: `2 February 1859`,
	},
	{
		id: 18058,
		countryId,
		name: `Miguel Miramón`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `2 February 1859`,
		leftOffice: `13 August 1860`,
	},
	{
		id: 18059,
		countryId,
		name: `José Ignacio Pavón`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `13 August 1860`,
		leftOffice: `15 August 1860`,
	},
	{
		id: 18060,
		countryId,
		name: `Miguel Miramón`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `15 August 1860`,
		leftOffice: `24 December 1860`,
	},
	{
		id: 18061,
		countryId,
		name: `Félix María Zuloaga`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `23 May 1861`,
		leftOffice: `28 December 1862`,
	},
	{
		id: 18062,
		countryId,
		name: `Juan Nepomuceno Almonte`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `11 July 1863`,
		leftOffice: `10 April 1864`,
	},
	{
		id: 18063,
		countryId,
		name: `José Mariano Salas`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `11 July 1863`,
		leftOffice: `10 April 1864`,
	},
	{
		id: 18064,
		countryId,
		name: `Pelagio Antonio de Labastida`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `19 October 1863`,
		leftOffice: `10 April 1864`,
	},
	{
		id: 18065,
		countryId,
		name: `Benito Juárez`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `18 December 1857`,
		leftOffice: `18 July 1872`,
	},
	{
		id: 18066,
		countryId,
		name: `Sebastián Lerdo de Tejada`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `18 July 1872`,
		leftOffice: `20 November 1876`,
	},
	{
		id: 18067,
		countryId,
		name: `José María Iglesias`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `26 October 1876`,
		leftOffice: `28 November 1876`,
	},
	{
		id: 18068,
		countryId,
		name: `Porfirio Díaz`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `28 November 1876`,
		leftOffice: `6 December 1876`,
	},
	{
		id: 18069,
		countryId,
		name: `Juan N. Méndez`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `6 December 1876`,
		leftOffice: `17 February 1877`,
	},
	{
		id: 18070,
		countryId,
		name: `Porfirio Díaz`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `17 February 1877`,
		leftOffice: `1 December 1880`,
	},
	{
		id: 18071,
		countryId,
		name: `Manuel González Flores`,
		party: `Liberal Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 December 1880`,
		leftOffice: `1 December 1884`,
	},
	{
		id: 18072,
		countryId,
		name: `Porfirio Díaz`,
		party: `National Porfirist party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1884`,
		leftOffice: `25 May 1911`,
	},
	{
		id: 18073,
		countryId,
		name: `Francisco León de la Barra`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 May 1911`,
		leftOffice: `6 November 1911`,
	},
	{
		id: 18074,
		countryId,
		name: `Francisco I. Madero`,
		party: `Progressive Constitutionalist Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `6 November 1911`,
		leftOffice: `19 February 1913`,
	},
	{
		id: 18075,
		countryId,
		name: `Pedro Lascuráin`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `19 February 1913`,
		leftOffice: `19 February 1913`,
	},
	{
		id: 18076,
		countryId,
		name: `Victoriano Huerta`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `19 February 1913`,
		leftOffice: `15 July 1914`,
	},
	{
		id: 18077,
		countryId,
		name: `Francisco S. Carvajal`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 July 1914`,
		leftOffice: `13 August 1914`,
	},
	{
		id: 18078,
		countryId,
		name: `Venustiano Carranza`,
		party: `Liberal Constitutionalist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `13 August 1914`,
		leftOffice: `21 May 1920`,
	},
	{
		id: 18079,
		countryId,
		name: `Adolfo de la Huerta`,
		party: `Liberal Constitutionalist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `21 May 1920`,
		leftOffice: `1 December 1920`,
	},
	{
		id: 18080,
		countryId,
		name: `Álvaro Obregón`,
		party: `Laborist Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 December 1920`,
		leftOffice: `1 December 1924`,
	},
	{
		id: 18081,
		countryId,
		name: `Plutarco Elías Calles`,
		party: `Laborist Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 December 1924`,
		leftOffice: `1 December 1928`,
	},
	{
		id: 18082,
		countryId,
		name: `Emilio Portes Gil`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1928`,
		leftOffice: `5 February 1930`,
	},
	{
		id: 18083,
		countryId,
		name: `Pascual Ortiz Rubio`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `5 February 1930`,
		leftOffice: `4 September 1932`,
	},
	{
		id: 18084,
		countryId,
		name: `Abelardo L. Rodríguez`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `4 September 1932`,
		leftOffice: `1 December 1934`,
	},
	{
		id: 18085,
		countryId,
		name: `Lázaro Cárdenas`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.LEFT,
		tookOffice: `1 December 1934`,
		leftOffice: `1 December 1940`,
	},
	{
		id: 18086,
		countryId,
		name: `Manuel Ávila Camacho`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1940`,
		leftOffice: `1 December 1946`,
	},
	{
		id: 18087,
		countryId,
		name: `Miguel Alemán Valdés`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1946`,
		leftOffice: `1 December 1952`,
	},
	{
		id: 18088,
		countryId,
		name: `Adolfo Ruiz Cortines`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1952`,
		leftOffice: `1 December 1958`,
	},
	{
		id: 18089,
		countryId,
		name: `Adolfo López Mateos`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1958`,
		leftOffice: `1 December 1964`,
	},
	{
		id: 18090,
		countryId,
		name: `Gustavo Díaz Ordaz`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1964`,
		leftOffice: `1 December 1970`,
	},
	{
		id: 18091,
		countryId,
		name: `Luis Echeverría Álvarez`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1970`,
		leftOffice: `1 December 1976`,
	},
	{
		id: 18092,
		countryId,
		name: `Lopez Portillo`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1976`,
		leftOffice: `1 December 1982`,
	},
	{
		id: 18093,
		countryId,
		name: `Miguel de la Madrid`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1982`,
		leftOffice: `1 December 1988`,
	},
	{
		id: 18094,
		countryId,
		name: `Carlos Salinas de Gortari`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1988`,
		leftOffice: `1 December 1994`,
	},
	{
		id: 18095,
		countryId,
		name: `Ernesto Zedillo Ponce de Leon`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 1994`,
		leftOffice: `1 December 2000`,
	},
	{
		id: 18096,
		countryId,
		name: `Vicente Fox`,
		party: `National Action Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 2000`,
		leftOffice: `1 December 2006`,
	},
	{
		id: 18097,
		countryId,
		name: `Felipe Calderon`,
		party: `National Action Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 2006`,
		leftOffice: `1 December 2012`,
	},
	{
		id: 18098,
		countryId,
		name: `Enrique Pena Nieto`,
		party: `Institutional Revolutionary Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 December 2012`,
		leftOffice: `1 December 2018`,
	},
	{
		id: 18099,
		countryId,
		name: `Andrés Manuel López Obrador`,
		party: `National Regeneration Movement`,
		leaning: leanings.LEFT,
		tookOffice: `1 December 2018`,
		leftOffice: `1 October 2024`,
	},
	{
		id: 18100,
		countryId,
		name: `Claudia Sheinbaum`,
		party: `National Regeneration Movement`,
		leaning: leanings.LEFT,
		tookOffice: `1 October 2024`,
		leftOffice: null
	}
];
