import type { LeaderSeed } from '../../src/data/types';
import { leanings } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/President_of_Nicaragua`;

const countryId = 7;

export const nicaragua: LeaderSeed[] = [
	{
		id: 19000,
		countryId,
		name: `Captaincy General of Guatemala`,
		party: `Kingdom of Spain`,
		leaning: leanings.MONARCHY,
		tookOffice: `1 January 1609`,
		leftOffice: `15 September 1821`,
	},
	{
		id: 19001,
		countryId,
		name: `Gabino Gaínza`,
		party: `Military / Central American Independence`,
		leaning: leanings.MILITARY,
		tookOffice: `15 September 1821`,
		leftOffice: `5 January 1822`,
	},
	{
		id: 19002,
		countryId,
		name: `Agustín de Iturbide`,
		party: `First Mexican Empire`,
		leaning: leanings.MONARCHY,
		tookOffice: `5 January 1822`,
		leftOffice: `1 July 1823`,
	},
	{
		id: 19003,
		countryId,
		name: `Vicente Filísola - Federal Republic of Central America`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 July 1823`,
		leftOffice: `10 July 1823`,
	},
	{
		id: 19004,
		countryId,
		name: `First Triumvirate - Federal Republic of Central America`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 July 1823`,
		leftOffice: `4 October 1823`,
	},
	{
		id: 19005,
		countryId,
		name: `Second Triumvirate - Federal Republic of Central America`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `4 October 1823`,
		leftOffice: `29 April 1825`,
	},
	{
		id: 19006,
		countryId,
		name: `Manuel José Arce - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `29 April 1825`,
		leftOffice: `13 April 1829`,
	},
	{
		id: 19007,
		countryId,
		name: `Mariano Beltranena y Llano - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `13 April 1829`,
		leftOffice: `14 June 1829`,
	},
	{
		id: 19008,
		countryId,
		name: `Francisco Morazán - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `14 June 1829`,
		leftOffice: `25 June 1829`,
	},
	{
		id: 19009,
		countryId,
		name: `José Francisco Barrundia - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `25 June 1829`,
		leftOffice: `16 September 1830`,
	},
	{
		id: 19010,
		countryId,
		name: `Francisco Morazán - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `16 September 1830`,
		leftOffice: `16 September 1834`,
	},
	{
		id: 19011,
		countryId,
		name: `José Gregorio Salazar - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `16 September 1834`,
		leftOffice: `14 February 1835`,
	},
	{
		id: 19012,
		countryId,
		name: `Francisco Morazán - Federal Republic of Central America`,
		party: `Liberal`,
		leaning: leanings.LEFT,
		tookOffice: `14 February 1835`,
		leftOffice: `30 April 1838`,
	},
	// Independence from the Federal Republic of Central America
	{
		id: 19013,
		countryId,
		name: `José Núñez`,
		party: `Legitimist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `30 April 1838`,
		leftOffice: `1 January 1839`,
	},
	{
		id: 19014,
		countryId,
		name: `Joaquín del Cossío`,
		party: `Legitimist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 January 1839`,
		leftOffice: `5 January 1839`,
	},
	{
		id: 19015,
		countryId,
		name: `Evaristo Rocha`,
		party: `Legitimist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `5 January 1839`,
		leftOffice: `30 June 1839`,
	},
	{
		id: 19016,
		countryId,
		name: `Patricio Rivas`,
		party: `Democratic Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `30 June 1839`,
		leftOffice: `27 July 1839`,
	},
	{
		id: 19017,
		countryId,
		name: `Joaquín del Cossío`,
		party: `Legitimist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `27 July 1839`,
		leftOffice: `20 October 1839`,
	},
	{
		id: 19018,
		countryId,
		name: `Hilario Ulloa`,
		party: `Legitimist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `20 October 1839`,
		leftOffice: `7 November 1839`,
	},
	{
		id: 19019,
		countryId,
		name: `Tomás Valladares`,
		party: `Democratic Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `7 November 1839`,
		leftOffice: `21 September 1840`,
	},
	{
		id: 19020,
		countryId,
		name: `Patricio Rivas`,
		party: `Democratic Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `21 September 1840`,
		leftOffice: `4 March 1841`,
	},
	{
		id: 19021,
		countryId,
		name: `Pablo Buitrago`,
		party: `Legitimist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `4 March 1841`,
		leftOffice: `1 April 1843`,
	},
	{
		id: 19022,
		countryId,
		name: `Juan de Dios Orozco`,
		party: `Legitimist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 April 1843`,
		leftOffice: `31 May 1843`,
	},
	{
		id: 19023,
		countryId,
		name: `Manuel Pérez`,
		party: `Democratic Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `31 May 1843`,
		leftOffice: `4 November 1844`,
	},
	{
		id: 19024,
		countryId,
		name: `Emiliano Madriz`,
		party: `Democratic Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `4 November 1844`,
		leftOffice: `16 December 1844`,
	},
	{
		id: 19025,
		countryId,
		name: `Silvestre Selva`,
		party: `Legitimist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `16 December 1844`,
		leftOffice: `20 January 1845`,
	},
	{
		id: 19026,
		countryId,
		name: `Blas Antonio Sáenz`,
		party: `Legitimist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `20 January 1845`,
		leftOffice: `4 April 1845`,
	},
	{
		id: 19027,
		countryId,
		name: `José León Sandoval`,
		party: `Republican Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `4 April 1845`,
		leftOffice: `12 March 1847`,
	},
	{
		id: 19028,
		countryId,
		name: `Miguel Ramón Morales`,
		party: `Legitimist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 March 1847`,
		leftOffice: `6 April 1847`,
	},
	{
		id: 19029,
		countryId,
		name: `José María Guerrero`,
		party: `Republican Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `6 April 1847`,
		leftOffice: `1 January 1849`,
	},
	{
		id: 19030,
		countryId,
		name: `Toribio Terán`,
		party: `Legitimist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 January 1849`,
		leftOffice: `8 March 1849`,
	},
	{
		id: 19031,
		countryId,
		name: `Benito Rosales`,
		party: `Legitimist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 March 1849`,
		leftOffice: `1 April 1849`,
	},
	{
		id: 19032,
		countryId,
		name: `Norberto Ramírez`,
		party: `Legitimist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 April 1849`,
		leftOffice: `1 April 1851`,
	},
	{
		id: 19033,
		countryId,
		name: `Justo Abaunza`,
		party: `Legitimist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 April 1851`,
		leftOffice: `5 May 1851`,
	},
	{
		id: 19034,
		countryId,
		name: `Laureano Pineda`,
		party: `Democratic Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `5 May 1851`,
		leftOffice: `4 August 1851`,
	},
	{
		id: 19035,
		countryId,
		name: `Justo Abaunza`,
		party: `Legitimist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `4 August 1851`,
		leftOffice: `11 November 1851`,
	},
	{
		id: 19040,
		countryId,
		name: `Laureano Pineda`,
		party: `Democratic Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `11 November 1851`,
		leftOffice: `1 April 1853`,
	},
	{
		id: 19041,
		countryId,
		name: `Fruto Chamorro`,
		party: `Legitimist Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 April 1853`,
		leftOffice: `30 April 1854`,
	},
	{
		id: 19044,
		countryId,
		name: `Fruto Chamorro`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `30 April 1854`,
		leftOffice: `12 March 1855`,
	},
	{
		id: 19045,
		countryId,
		name: `José María Estrada`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 March 1855`,
		leftOffice: `30 October 1855`,
	},
	{
		id: 19046,
		countryId,
		name: `Patricio Rivas`,
		party: `Democratic Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `30 October 1855`,
		leftOffice: `24 June 1857`,
	},
	{
		id: 19048,
		countryId,
		name: `Máximo Jerez and Tomás Martínez`,
		party: `Non Partisan`,
		leaning: leanings.CENTRIST,
		tookOffice: `24 June 1857`,
		leftOffice: `15 November 1857`,
	},
	{
		id: 19049,
		countryId,
		name: `Tomás Martínez`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 November 1857`,
		leftOffice: `1 March 1867`,
	},
	{
		id: 19050,
		countryId,
		name: `Fernando Guzmán Solórzano`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1867`,
		leftOffice: `1 March 1871`,
	},
	{
		id: 19051,
		countryId,
		name: `José Vicente Cuadra`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1871`,
		leftOffice: `1 March 1875`,
	},
	{
		id: 19052,
		countryId,
		name: `Pedro Joaquín Chamorro Alfaro`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1875`,
		leftOffice: `1 March 1879`,
	},
	{
		id: 19053,
		countryId,
		name: `Joaquín Zavala`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1879`,
		leftOffice: `1 March 1883`,
	},
	{
		id: 19054,
		countryId,
		name: `Adán Cárdenas`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1883`,
		leftOffice: `1 March 1887`,
	},
	{
		id: 19057,
		countryId,
		name: `Evaristo Carazo`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1887`,
		leftOffice: `5 August 1889`,
	},
	{
		id: 19058,
		countryId,
		name: `Roberto Sacasa`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `5 August 1889`,
		leftOffice: `1 January 1891`,
	},
	{
		id: 19059,
		countryId,
		name: `Ignacio Chávez`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 January 1891`,
		leftOffice: `1 March 1891`,
	},
	{
		id: 19060,
		countryId,
		name: `Roberto Sacasa`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1891`,
		leftOffice: `25 July 1893`,
	},
	{
		id: 19061,
		countryId,
		name: `José Santos Zelaya`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `25 July 1893`,
		leftOffice: `21 December 1909`,
	},
	{
		id: 19062,
		countryId,
		name: `José Madriz`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `21 December 1909`,
		leftOffice: `20 August 1910`,
	},
	{
		id: 19063,
		countryId,
		name: `José Dolores Estrada`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `20 August 1910`,
		leftOffice: `27 August 1910`,
	},
	{
		id: 19064,
		countryId,
		name: `Luis Mena`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `27 August 1910`,
		leftOffice: `30 August 1910`,
	},
	{
		id: 19065,
		countryId,
		name: `Juan José Estrada`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `30 August 1910`,
		leftOffice: `9 May 1911`,
	},
	{
		id: 19066,
		countryId,
		name: `Adolfo Díaz`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `9 May 1911`,
		leftOffice: `1 January 1917`,
	},
	{
		id: 19067,
		countryId,
		name: `Emiliano Chamorro Vargas`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 January 1917`,
		leftOffice: `1 January 1921`,
	},
	{
		id: 19068,
		countryId,
		name: `Diego Manuel Chamorro`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 January 1921`,
		leftOffice: `12 October 1923`,
	},
	{
		id: 19069,
		countryId,
		name: `Rosendo Chamorro`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `12 October 1923`,
		leftOffice: `27 October 1923`,
	},
	{
		id: 19070,
		countryId,
		name: `Bartolomé Martínez`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `27 October 1923`,
		leftOffice: `1 January 1925`,
	},
	{
		id: 19071,
		countryId,
		name: `Carlos José Solórzano`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 January 1925`,
		leftOffice: `14 March 1926`,
	},
	{
		id: 19072,
		countryId,
		name: `Emiliano Chamorro Vargas`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `14 March 1926`,
		leftOffice: `14 November 1926`,
	},
	{
		id: 19073,
		countryId,
		name: `Adolfo Díaz`,
		party: `Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `14 November 1926`,
		leftOffice: `1 January 1929`,
	},
	{
		id: 19074,
		countryId,
		name: `Jose Maria Moncada Tapia`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 January 1929`,
		leftOffice: `1 January 1933`,
	},
	{
		id: 19075,
		countryId,
		name: `Juan Bautista Sacasa`,
		party: `Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 January 1933`,
		leftOffice: `9 June 1936`,
	},
	{
		id: 19076,
		countryId,
		name: `Carlos Alberto Brenes`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `9 June 1936`,
		leftOffice: `1 January 1937`,
	},
	{
		id: 19077,
		countryId,
		name: `Anastasio Somoza García`,
		party: `Military / Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 January 1937`,
		leftOffice: `1 May 1947`,
	},
	{
		id: 19078,
		countryId,
		name: `Leonardo Argüello Barreto`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 May 1947`,
		leftOffice: `26 May 1947`,
	},
	{
		id: 19079,
		countryId,
		name: `Benjamín Lacayo Sacasa`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `26 May 1947`,
		leftOffice: `15 August 1947`,
	},
	{
		id: 19080,
		countryId,
		name: `Víctor Manuel Román y Reyes`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `15 August 1947`,
		leftOffice: `21 May 1950`,
	},
	{
		id: 19081,
		countryId,
		name: `Anastasio Somoza García`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `21 May 1950`,
		leftOffice: `29 September 1956`,
	},
	{
		id: 19082,
		countryId,
		name: `Luis Somoza Debayle`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `29 September 1956`,
		leftOffice: `1 May 1963`,
	},
	{
		id: 19083,
		countryId,
		name: `René Schick`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 May 1963`,
		leftOffice: `4 August 1966`,
	},
	{
		id: 19084,
		countryId,
		name: `Lorenzo Guerrero`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `4 August 1966`,
		leftOffice: `1 May 1967`,
	},
	{
		id: 19085,
		countryId,
		name: `Anastasio Somoza DeBayle`,
		party: `Military / Nationalist Liberal Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 May 1967`,
		leftOffice: `1 May 1972`,
	},
	{
		id: 19086,
		countryId,
		name: `Liberal-Conservative Junta`,
		party: `Nationalist Liberal Party / Social Conservative Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 May 1972`,
		leftOffice: `1 December 1974`,
	},
	{
		id: 19087,
		countryId,
		name: `Anastasio Somoza DeBayle`,
		party: `Military / Nationalist Liberal Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 December 1974`,
		leftOffice: `17 July 1979`,
	},
	{
		id: 19088,
		countryId,
		name: `Francisco Urcuyo`,
		party: `Nationalist Liberal Party`,
		leaning: leanings.RIGHT,
		tookOffice: `17 July 1979`,
		leftOffice: `18 July 1979`,
	},
	{
		id: 19089,
		countryId,
		name: `Junta of National Reconstruction`,
		party: `Sandinista National Liberation Front`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `18 July 1979`,
		leftOffice: `10 January 1985`,
	},
	{
		id: 19090,
		countryId,
		name: `Daniel Ortega`,
		party: `Sandinista National Liberation Front`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `10 January 1985`,
		leftOffice: `25 April 1990`,
	},
	{
		id: 19091,
		countryId,
		name: `Violeta Chamorro`,
		party: `Democratic Union of Liberation`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 April 1990`,
		leftOffice: `10 January 1997`,
	},
	{
		id: 19092,
		countryId,
		name: `José Arnoldo Alemán Lacayo`,
		party: `Constitutionalist Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 January 1997`,
		leftOffice: `10 January 2002`,
	},
	{
		id: 19093,
		countryId,
		name: `Enrique Bolaños Geyer`,
		party: `Constitutionalist Liberal Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 January 2002`,
		leftOffice: `10 January 2007`,
	},
	{
		id: 19094,
		countryId,
		name: `Daniel Ortega`,
		party: `Sandinista National Liberation Front`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `10 January 2007`,
		leftOffice: null,
	},
];
