import type { LeaderSeed } from '../../src/data/types';
import { leanings } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_heads_of_state_of_Panama`;

const countryId = 9;

export const panama: LeaderSeed[] = [
	{
		id: 20000,
		countryId,
		name: `Viceroyalty of New Granada`,
		party: `Kingdom of Spain`,
		leaning: leanings.MONARCHY,
		tookOffice: `27 May 1717`,
		leftOffice: `22 May 1810`,
	},
	{
		id: 20001,
		countryId,
		name: `First Republic of New Granada`,
		party: `First Republic of New Granada`,
		leaning: leanings.MILITARY,
		tookOffice: `22 May 1810`,
		leftOffice: `6 May 1816`,
	},
	{
		id: 20002,
		countryId,
		name: `Viceroyalty of New Granada`,
		party: `Kingdom of Spain`,
		leaning: leanings.MONARCHY,
		tookOffice: `6 May 1816`,
		leftOffice: `15 February 1819`,
	},
	{
		id: 20003,
		countryId,
		name: `Simón Bolívar - Gran Colombia`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `15 February 1819`,
		leftOffice: `4 May 1830`,
	},
	{
		id: 20004,
		countryId,
		name: `Joaquín de Mosquera y Arboleda - Gran Colombia`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `4 May 1830`,
		leftOffice: `4 September 1830`,
	},
	{
		id: 20005,
		countryId,
		name: `Rafael Urdaneta y Faría - Gran Colombia`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `4 May 1830`,
		leftOffice: `30 April 1831`,
	},
	{
		id: 20006,
		countryId,
		name: `Domingo Caycedo y Sanz de Santamaría - Gran Colombia`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `30 April 1831`,
		leftOffice: `21 November 1831`,
	},
	{
		id: 20007,
		countryId,
		name: `José María Obando del Campo - Gran Colombia`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `21 November 1831`,
		leftOffice: `10 March 1832`,
	},
	{
		id: 20008,
		countryId,
		name: `Francisco de Paula Santander y Omaña - Republic of New Granada`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `10 March 1832`,
		leftOffice: `1 April 1837`,
	},
	{
		id: 20009,
		countryId,
		name: `José Ignacio de Márquez Barreto - Republic of New Granada`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `1 April 1837`,
		leftOffice: `1 April 1841`,
	},
	{
		id: 20010,
		countryId,
		name: `Pedro Alcántara Herrán Martínez - Republic of New Granada`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `1 April 1841`,
		leftOffice: `1 April 1845`,
	},
	{
		id: 20011,
		countryId,
		name: `Tomás Cipriano de Mosquera y Arboleda - Republic of New Granada`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `1 April 1845`,
		leftOffice: `1 April 1849`,
	},
	{
		id: 20012,
		countryId,
		name: `José Hilario López Valdéz - Republic of New Granada`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1849`,
		leftOffice: `1 April 1853`,
	},
	{
		id: 20013,
		countryId,
		name: `José María Obando del Campo - Republic of New Granada`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1853`,
		leftOffice: `17 April 1854`,
	},
	{
		id: 20014,
		countryId,
		name: `José María Melo y Ortiz - Republic of New Granada`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `17 April 1854`,
		leftOffice: `4 December 1854`,
	},
	{
		id: 20015,
		countryId,
		name: `Manuel María Mallarino Ibargüen - Republic of New Granada`,
		party: `Colombian Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `4 December 1854`,
		leftOffice: `1 April 1857`,
	},
	{
		id: 20016,
		countryId,
		name: `Mariano Ospina Rodríguez - Granadine Confederation`,
		party: `Colombian Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 April 1857`,
		leftOffice: `1 April 1861`,
	},
	{
		id: 20017,
		countryId,
		name: `Bartolomé Calvo Díaz - Granadine Confederation`,
		party: `Colombian Conservative Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 April 1861`,
		leftOffice: `18 July 1861`,
	},
	{
		id: 20018,
		countryId,
		name: `Juan José Nieto Gil - Granadine Confederation`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `25 January 1861`,
		leftOffice: `18 July 1861`,
	},
	{
		id: 20019,
		countryId,
		name: `Tomás Cipriano de Mosquera y Arboleda - Granadine Confederation`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `18 July 1861`,
		leftOffice: `4 February 1863`,
	},
	{
		id: 20020,
		countryId,
		name: `Tomás Cipriano de Mosquera y Arboleda - United States of Colombia`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `14 May 1863`,
		leftOffice: `1 April 1864`,
	},
	{
		id: 20021,
		countryId,
		name: `Manuel Murillo Toro - United States of Colombia`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1864`,
		leftOffice: `1 April 1866`,
	},
	{
		id: 20022,
		countryId,
		name: `Tomás Cipriano de Mosquera y Arboleda - United States of Colombia`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1866`,
		leftOffice: `23 May 1867`,
	},
	{
		id: 20023,
		countryId,
		name: `Santos Acosta Castillo - United States of Colombia`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `23 May 1867`,
		leftOffice: `1 April 1868`,
	},
	{
		id: 20024,
		countryId,
		name: `Santos Gutiérrez Prieto - United States of Colombia`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1868`,
		leftOffice: `1 April 1870`,
	},
	{
		id: 20025,
		countryId,
		name: `Eustorgio Salgar Moreno - United States of Colombia`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1870`,
		leftOffice: `1 April 1872`,
	},
	{
		id: 20026,
		countryId,
		name: `Manuel Murillo Toro - United States of Colombia`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1872`,
		leftOffice: `1 April 1874`,
	},
	{
		id: 20027,
		countryId,
		name: `Santiago Pérez de Manosalbas - United States of Colombia`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1874`,
		leftOffice: `1 April 1876`,
	},
	{
		id: 20028,
		countryId,
		name: `Aquileo Parra Gómez - United States of Colombia`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1876`,
		leftOffice: `1 April 1878`,
	},
	{
		id: 20029,
		countryId,
		name: `Julián Trujillo Largacha - United States of Colombia`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1878`,
		leftOffice: `1 April 1880`,
	},
	{
		id: 20030,
		countryId,
		name: `Rafael Núñez Moledo - United States of Colombia`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1880`,
		leftOffice: `1 April 1882`,
	},
	{
		id: 20031,
		countryId,
		name: `Rafael Núñez MoledoFrancisco Javier Zaldúa y Racines - United States of Colombia`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1882`,
		leftOffice: `21 December 1882`,
	},
	{
		id: 20032,
		countryId,
		name: `José Eusebio Otálora Martínez - United States of Colombia`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `21 December 1882`,
		leftOffice: `1 April 1884`,
	},
	{
		id: 20033,
		countryId,
		name: `Rafael Núñez Moledo - United States of Colombia`,
		party: `Colombian Liberal Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 April 1884`,
		leftOffice: `1 April 1886`,
	},
	{
		id: 20034,
		countryId,
		name: `Rafael Núñez Moledo - United States of Colombia`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 April 1886`,
		leftOffice: `18 September 1894`,
	},
	{
		id: 20035,
		countryId,
		name: `Miguel Antonio Caro Tobar - Republic of Colombia`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 September 1894`,
		leftOffice: `7 August 1898`,
	},
	{
		id: 20036,
		countryId,
		name: `Rafael Núñez Moledo - Republic of Colombia`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 April 1886`,
		leftOffice: `18 September 1894`,
	},
	{
		id: 20037,
		countryId,
		name: `Miguel Antonio Caro - Republic of Colombia`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 September 1894`,
		leftOffice: `7 August 1898`,
	},
	{
		id: 20038,
		countryId,
		name: `Manuel Antonio Sanclemente - Republic of Colombia`,
		party: `National Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1898`,
		leftOffice: `31 July 1900`,
	},
	{
		id: 20039,
		countryId,
		name: `José Manuel Marroquín - Republic of Colombia`,
		party: `Colombian Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `31 July 1900`,
		leftOffice: `3 November 1903`,
	},
	// Indepedence from Colombia
	{
		id: 20040,
		countryId,
		name: `Republic of Panama`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 November 1903`,
		leftOffice: `20 February 1904`,
	},
	{
		id: 20041,
		countryId,
		name: `Manuel Amador Guerrero`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `20 February 1904`,
		leftOffice: `23 June 1907`,
	},
	{
		id: 20042,
		countryId,
		name: `José Domingo de Obaldía`,
		party: `National Liberal party`,
		leaning: leanings.CENTRIST,
		tookOffice: `24 June 1907`,
		leftOffice: `27 December 1907`,
	},
	{
		id: 20043,
		countryId,
		name: `Manuel Amador Guerrero`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `29 December 1907`,
		leftOffice: `1 October 1908`,
	},
	{
		id: 20044,
		countryId,
		name: `José Domingo de Obaldía`,
		party: `National Liberal party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 October 1908`,
		leftOffice: `1 March 1910`,
	},
	{
		id: 20045,
		countryId,
		name: `Carlos Antonio Mendoza`,
		party: `National Liberal party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1910`,
		leftOffice: `1 October 1910`,
	},
	{
		id: 20046,
		countryId,
		name: `Federico Boyd`,
		party: `National Liberal party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 October 1910`,
		leftOffice: `5 October 1910`,
	},
	{
		id: 20047,
		countryId,
		name: `Pablo Arosemena`,
		party: `National Liberal party`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 October 1910`,
		leftOffice: `1 October 1912`,
	},
	{
		id: 20048,
		countryId,
		name: `Belisario Porras Barahona`,
		party: `National Liberal party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 October 1912`,
		leftOffice: `1 October 1916`,
	},
	{
		id: 20049,
		countryId,
		name: `Ramón Maximiliano Valdés`,
		party: `National Liberal party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 October 1916`,
		leftOffice: `3 June 1918`,
	},
	{
		id: 20050,
		countryId,
		name: `Ciro Luis Urriola`,
		party: `National Liberal party`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 June 1918`,
		leftOffice: `1 October 1918`,
	},
	{
		id: 20051,
		countryId,
		name: `Pedro Antonio Díaz`,
		party: `Conservative Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 October 1918`,
		leftOffice: `12 October 1918`,
	},
	{
		id: 20052,
		countryId,
		name: `Belisario Porras Barahona`,
		party: `National Liberal party`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 October 1918`,
		leftOffice: `30 January 1920`,
	},
	{
		id: 20053,
		countryId,
		name: `Ernesto Tisdel Lefevre`,
		party: `National Liberal party`,
		leaning: leanings.CENTRIST,
		tookOffice: `30 January 1920`,
		leftOffice: `1 October 1920`,
	},
	{
		id: 20054,
		countryId,
		name: `Belisario Porras Barahona`,
		party: `National Liberal party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 October 1920`,
		leftOffice: `1 October 1924`,
	},
	{
		id: 20055,
		countryId,
		name: `Rodolfo Chiari`,
		party: `National Liberal party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 October 1924`,
		leftOffice: `1 October 1928`,
	},
	{
		id: 20056,
		countryId,
		name: `Ernesto Tisdel Lefevre`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `30 January 1920`,
		leftOffice: `1 October 1920`,
	},
	{
		id: 20057,
		countryId,
		name: `Belisario Porras Barahona`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 October 1920`,
		leftOffice: `1 October 1924`,
	},
	{
		id: 20058,
		countryId,
		name: `Rodolfo Chiari`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 October 1924`,
		leftOffice: `1 October 1928`,
	},
	{
		id: 20059,
		countryId,
		name: `Florencio Harmodio Arosemena`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 October 1928`,
		leftOffice: `3 January 1931`,
	},
	{
		id: 20060,
		countryId,
		name: `Harmodio Arias Madrid`,
		party: `National Revolutionary Party`,
		leaning: leanings.RIGHT,
		tookOffice: `3 January 1931`,
		leftOffice: `16 January 1931`,
	},
	{
		id: 20061,
		countryId,
		name: `Ricardo Joaquín Alfaro Jované`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `16 January 1931`,
		leftOffice: `5 June 1932`,
	},
	{
		id: 20062,
		countryId,
		name: `Harmodio Arias Madrid`,
		party: `National Revolutionary Party`,
		leaning: leanings.RIGHT,
		tookOffice: `5 June 1932`,
		leftOffice: `1 October 1936`,
	},
	{
		id: 20063,
		countryId,
		name: `Juan Demóstenes Arosemena`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 October 1936`,
		leftOffice: `16 December 1939`,
	},
	{
		id: 20064,
		countryId,
		name: `Ezequiel Fernández`,
		party: `National Revolutionary Party`,
		leaning: leanings.RIGHT,
		tookOffice: `16 December 1939`,
		leftOffice: `18 December 1939`,
	},
	{
		id: 20065,
		countryId,
		name: `Augusto Samuel Boyd`,
		party: `National Revolutionary Party`,
		leaning: leanings.RIGHT,
		tookOffice: `18 December 1939`,
		leftOffice: `1 October 1940`,
	},
	{
		id: 20066,
		countryId,
		name: `Arnulfo Arias`,
		party: `Panameñista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 October 1940`,
		leftOffice: `9 October 1941`,
	},
	{
		id: 20067,
		countryId,
		name: `Ricardo Adolfo de la Guardia Arango`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `9 October 1941`,
		leftOffice: `15 June 1945`,
	},
	{
		id: 20068,
		countryId,
		name: `Enrique Adolfo Jiménez`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 June 1945`,
		leftOffice: `7 August 1948`,
	},
	{
		id: 20069,
		countryId,
		name: `Domingo Díaz Arosemena`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 August 1948`,
		leftOffice: `28 July 1949`,
	},
	{
		id: 20070,
		countryId,
		name: `Daniel Chanis Pinzón`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `28 July 1949`,
		leftOffice: `20 November 1949`,
	},
	{
		id: 20071,
		countryId,
		name: `Roberto Francisco Chiari Remón`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 November 1949`,
		leftOffice: `24 November 1949`,
	},
	{
		id: 20072,
		countryId,
		name: `Arnulfo Arias`,
		party: `Panameñista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `24 November 1949`,
		leftOffice: `9 May 1951`,
	},
	{
		id: 20073,
		countryId,
		name: `Alcibíades Arosemena`,
		party: `Authentic Revolutionary Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `9 May 1951`,
		leftOffice: `1 October 1952`,
	},
	{
		id: 20074,
		countryId,
		name: `José Antonio Remón Cantera`,
		party: `National Patriotic Coalition`,
		leaning: leanings.RIGHT,
		tookOffice: `1 October 1952`,
		leftOffice: `2 January 1955`,
	},
	{
		id: 20075,
		countryId,
		name: `José Ramón Guizado`,
		party: `National Patriotic Coalition`,
		leaning: leanings.RIGHT,
		tookOffice: `2 January 1955`,
		leftOffice: `29 March 1955`,
	},
	{
		id: 20076,
		countryId,
		name: `Ricardo Arias`,
		party: `National Patriotic Coalition`,
		leaning: leanings.RIGHT,
		tookOffice: `29 March 1955`,
		leftOffice: `1 October 1956`,
	},
	{
		id: 20077,
		countryId,
		name: `Ernesto de la Guardia`,
		party: `National Patriotic Coalition`,
		leaning: leanings.RIGHT,
		tookOffice: `1 October 1956`,
		leftOffice: `1 October 1960`,
	},
	{
		id: 20078,
		countryId,
		name: `Roberto Francisco Chiari Remón`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 October 1960`,
		leftOffice: `1 October 1964`,
	},
	{
		id: 20079,
		countryId,
		name: `Marco Aurelio Robles`,
		party: `National Liberal Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 October 1964`,
		leftOffice: `1 October 1968`,
	},
	{
		id: 20080,
		countryId,
		name: `Arnulfo Arias`,
		party: `Panameñista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 October 1968`,
		leftOffice: `11 October 1968`,
	},
	{
		id: 20081,
		countryId,
		name: `Omar Torrijos`,
		party: `National Guard of Panama`,
		leaning: leanings.MILITARY,
		tookOffice: `11 October 1968`,
		leftOffice: `31 July 1981`,
	},
	{
		id: 20082,
		countryId,
		name: `Rubén Darío Paredes`,
		party: `National Guard of Panama`,
		leaning: leanings.MILITARY,
		tookOffice: `31 July 1981`,
		leftOffice: `12 August 1983`,
	},
	{
		id: 20083,
		countryId,
		name: `Manuel Noriega`,
		party: `National Guard of Panama`,
		leaning: leanings.MILITARY,
		tookOffice: `12 August 1983`,
		leftOffice: `20 December 1989`,
	},
	{
		id: 20084,
		countryId,
		name: `Guillermo Endara`,
		party: `Panameñista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `20 December 1989`,
		leftOffice: `1 September 1994`,
	},
	{
		id: 20085,
		countryId,
		name: `Ernesto Pérez Balladares`,
		party: `Democratic Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 September 1994`,
		leftOffice: `1 September 1999`,
	},
	{
		id: 20086,
		countryId,
		name: `Mireya Moscoso`,
		party: `Panameñista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 September 1999`,
		leftOffice: `1 September 2004`,
	},
	{
		id: 20087,
		countryId,
		name: `Martín Torrijos`,
		party: `Democratic Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 September 2004`,
		leftOffice: `1 July 2009`,
	},
	{
		id: 20088,
		countryId,
		name: `Ricardo Martinelli`,
		party: `Democratic Change`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 July 2009`,
		leftOffice: `1 July 2014`,
	},
	{
		id: 20089,
		countryId,
		name: `Juan Carlos Varela`,
		party: `Panameñista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 July 2014`,
		leftOffice: `1 July 2019`,
	},
	{
		id: 20090,
		countryId,
		name: `Laurentino Cortizo`,
		party: `Democratic Revolutionary Party`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `1 July 2019`,
		leftOffice: `1 July 2024`,
	},
	{
		id: 20091,
		countryId,
		name: `José Raúl Mulino`,
		party: `Realizing Goals`,
		leaning: leanings.RIGHT,
		tookOffice: `1 July 2024`,
		leftOffice: null,
	}
];
