import type { LeaderSeed } from '../../src/data/types';
import { leanings } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Peru`;

const countryId = 16;

export const peru: LeaderSeed[] = [
	{
		id: 22000,
		countryId,
		name: `Viceroyalty of Peru`,
		party: `Kingdom of Spain`,
		leaning: leanings.MONARCHY,
		tookOffice: `1 January 1542`,
		leftOffice: `3 August 1821`,
	},
	{
		id: 22001,
		countryId,
		name: `José de San Martín`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `3 August 1821`,
		leftOffice: `20 September 1822`,
	},
	{
		id: 22100,
		countryId,
		name: `Supreme Governing Junta - José de La Mar, Felipe Antonio Alvarado, Manuel Salazar y Baquíjano`,
		party: `Constituent Congress`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 September 1822`,
		leftOffice: `28 February 1823`,
	},
	{
		id: 22002,
		countryId,
		name: `José de la Riva Agüero`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `28 February 1823`,
		leftOffice: `23 June 1823`,
	},
	{
		id: 22003,
		countryId,
		name: `José Bernardo de Tagle`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `23 June 1823`,
		leftOffice: `10 February 1824`,
	},
	{
		id: 22004,
		countryId,
		name: `Simón Bolívar`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `10 February 1824`,
		leftOffice: `10 June 1827`,
	},
	{
		id: 22005,
		countryId,
		name: `José de La Mar`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `10 June 1827`,
		leftOffice: `7 June 1829`,
	},
	{
		id: 22006,
		countryId,
		name: `Agustín Gamarra`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `7 June 1829`,
		leftOffice: `21 December 1833`,
	},
	{
		id: 22007,
		countryId,
		name: `Luis José de Orbegoso`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `21 December 1833`,
		leftOffice: `25 February 1835`,
	},
	{
		id: 22008,
		countryId,
		name: `Felipe Salaverry`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `25 February 1835`,
		leftOffice: `7 February 1836`,
	},
	{
		id: 22009,
		countryId,
		name: `Andrés de Santa Cruz`,
		party: `Peru–Bolivian Confederation`,
		leaning: leanings.CENTRIST,
		tookOffice: `7 February 1836`,
		leftOffice: `20 January 1839`,
	},
	{
		id: 22010,
		countryId,
		name: `Agustín Gamarra`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `20 January 1839`,
		leftOffice: `18 November 1841`,
	},
	{
		id: 22011,
		countryId,
		name: `Manuel Menéndez`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 November 1841`,
		leftOffice: `16 August 1842`,
	},
	{
		id: 22912,
		countryId,
		name: `Juan Crisóstomo Torrico`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `16 August 1842`,
		leftOffice: `20 October 1842`,
	},
	{
		id: 22012,
		countryId,
		name: `Juan Francisco de Vidal`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `20 October 1842`,
		leftOffice: `27 March 1843`,
	},
	{
		id: 22013,
		countryId,
		name: `Manuel Ignacio de Vivanco`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `27 March 1843`,
		leftOffice: `17 June 1844`,
	},
	{
		id: 22014,
		countryId,
		name: `Manuel Menéndez`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `17 June 1844`,
		leftOffice: `20 April 1845`,
	},
	{
		id: 22015,
		countryId,
		name: `Ramón Castilla`,
		party: `Military`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `20 April 1845`,
		leftOffice: `20 April 1851`,
	},
	{
		id: 22016,
		countryId,
		name: `José Rufino Echenique`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `20 April 1851`,
		leftOffice: `5 January 1855`,
	},
	{
		id: 22017,
		countryId,
		name: `Ramón Castilla`,
		party: `Military`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `5 January 1855`,
		leftOffice: `24 October 1862`,
	},
	{
		id: 22018,
		countryId,
		name: `Miguel de San Román`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `24 October 1862`,
		leftOffice: `3 April 1863`,
	},
	{
		id: 22019,
		countryId,
		name: `Pedro Diez Canseco`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `3 April 1863`,
		leftOffice: `5 August 1863`,
	},
	{
		id: 22020,
		countryId,
		name: `Juan Antonio Pezet`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `5 August 1863`,
		leftOffice: `8 November 1865`,
	},
	{
		id: 22921,
		countryId,
		name: `Pedro Diez Canseco`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `8 November 1865`,
		leftOffice: `28 November 1865`,
	},
	{
		id: 22021,
		countryId,
		name: `Mariano Ignacio Prado`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `28 November 1865`,
		leftOffice: `15 February 1867`,
	},
	{
		id: 22022,
		countryId,
		name: `Mariano Ignacio Prado`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `15 February 1867`,
		leftOffice: `31 August 1867`,
	},
	{
		id: 22023,
		countryId,
		name: `Mariano Ignacio Prado`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `31 August 1867`,
		leftOffice: `7 January 1868`,
	},
	{
		id: 22024,
		countryId,
		name: `Mariano Ignacio Prado`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `7 January 1868`,
		leftOffice: `2 August 1868`,
	},
	{
		id: 22025,
		countryId,
		name: `José Balta`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `2 August 1868`,
		leftOffice: `22 July 1872`,
	},
	{
		id: 22026,
		countryId,
		name: `Tomás Gutiérrez`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `22 July 1872`,
		leftOffice: `27 July 1872`,
	},
	{
		id: 22027,
		countryId,
		name: `Mariano Herencia Zevallos`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `27 July 1872`,
		leftOffice: `2 August 1872`,
	},
	{
		id: 22028,
		countryId,
		name: `Manuel Pardo y Lavalle`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `2 August 1872`,
		leftOffice: `2 August 1876`,
	},
	{
		id: 22029,
		countryId,
		name: `Mariano Ignacio Prado`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `2 August 1876`,
		leftOffice: `18 December 1879`,
	},
	{
		id: 22030,
		countryId,
		name: `Luis La Puerta`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `18 December 1879`,
		leftOffice: `23 December 1879`,
	},
	{
		id: 22031,
		countryId,
		name: `Nicolás de Piérola`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `23 December 1879`,
		leftOffice: `28 July 1881`,
	},
	{
		id: 22032,
		countryId,
		name: `Nicolás de Piérola`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `31 July 1881`,
		leftOffice: `28 December 1881`,
	},
	{
		id: 22033,
		countryId,
		name: `Francisco García Calderón`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 March 1881`,
		leftOffice: `10 July 1881`,
	},
	{
		id: 22034,
		countryId,
		name: `Francisco García Calderón`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 July 1881`,
		leftOffice: `6 November 1881`,
	},
	{
		id: 22035,
		countryId,
		name: `Lizardo Montero`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `28 September 1881`,
		leftOffice: `28 October 1883`,
	},
	{
		id: 22036,
		countryId,
		name: `Miguel Iglesias`,
		party: `Military`,
		leaning: leanings.MILITARY,
		tookOffice: `30 December 1882`,
		leftOffice: `3 December 1885`,
	},
	{
		id: 22037,
		countryId,
		name: `Antonio Arenas`,
		party: `President of the Government Junta of Peru`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 December 1885`,
		leftOffice: `5 June 1886`,
	},
	{
		id: 22038,
		countryId,
		name: `Andrés Avelino Cáceres`,
		party: `Constitutional Party`,
		leaning: leanings.RIGHT,
		tookOffice: `5 June 1886`,
		leftOffice: `10 August 1890`,
	},
	{
		id: 22039,
		countryId,
		name: `Remigio Morales Bermúdez`,
		party: `Constitutional Party`,
		leaning: leanings.RIGHT,
		tookOffice: `10 August 1890`,
		leftOffice: `1 April 1894`,
	},
	{
		id: 22040,
		countryId,
		name: `Justiniano Borgoño Castañeda`,
		party: `Constitutional Party`,
		leaning: leanings.RIGHT,
		tookOffice: `1 April 1894`,
		leftOffice: `10 August 1894`,
	},
	{
		id: 22041,
		countryId,
		name: `Andrés Avelino Cáceres`,
		party: `Constitutional Party`,
		leaning: leanings.RIGHT,
		tookOffice: `10 August 1894`,
		leftOffice: `20 March 1895`,
	},
	{
		id: 22042,
		countryId,
		name: `Manuel Candamo`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `20 March 1895`,
		leftOffice: `8 September 1895`,
	},
	{
		id: 22043,
		countryId,
		name: `Nicolás de Piérola`,
		party: `Democratic Party of Peru`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `8 September 1895`,
		leftOffice: `8 September 1899`,
	},
	{
		id: 22044,
		countryId,
		name: `Eduardo López de Romaña`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `8 September 1899`,
		leftOffice: `8 September 1903`,
	},
	{
		id: 22045,
		countryId,
		name: `Manuel Candamo`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `8 September 1903`,
		leftOffice: `7 May 1904`,
	},
	{
		id: 22046,
		countryId,
		name: `Serapio Calderón`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `7 May 1904`,
		leftOffice: `24 September 1904`,
	},
	{
		id: 22047,
		countryId,
		name: `José Pardo`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `24 September 1904`,
		leftOffice: `24 September 1908`,
	},
	{
		id: 22048,
		countryId,
		name: `Augusto B. Leguía`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `24 September 1908`,
		leftOffice: `24 September 1912`,
	},
	{
		id: 22049,
		countryId,
		name: `Guillermo Billinghurst`,
		party: `Democratic Party of Peru`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `24 September 1912`,
		leftOffice: `4 February 1914`,
	},
	{
		id: 22050,
		countryId,
		name: `Óscar R. Benavides`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `4 February 1914`,
		leftOffice: `18 August 1915`,
	},
	{
		id: 22051,
		countryId,
		name: `José Pardo`,
		party: `Civilista Party`,
		leaning: leanings.RIGHT,
		tookOffice: `18 August 1915`,
		leftOffice: `4 July 1919`,
	},
	{
		id: 22052,
		countryId,
		name: `Augusto B. Leguía`,
		party: `Reformist Democratic Party`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `4 July 1919`,
		leftOffice: `25 August 1930`,
	},
	{
		id: 22053,
		countryId,
		name: `Manuel María Ponce Brousset`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `25 August 1930`,
		leftOffice: `27 August 1930`,
	},
	{
		id: 22054,
		countryId,
		name: `Luis Miguel Sánchez Cerro`,
		party: `Revolutionary Union`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `27 August 1930`,
		leftOffice: `1 March 1931`,
	},
	{
		id: 22055,
		countryId,
		name: `Ricardo Leoncio Elías Arias`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 March 1931`,
		leftOffice: `5 March 1931`,
	},
	{
		id: 22056,
		countryId,
		name: `Gustavo Jiménez`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `5 March 1931`,
		leftOffice: `11 March 1931`,
	},
	{
		id: 22057,
		countryId,
		name: `David Samanez Ocampo`,
		party: `Democratic Party of Peru`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `11 March 1931`,
		leftOffice: `8 December 1931`,
	},
	{
		id: 22058,
		countryId,
		name: `Luis Miguel Sánchez Cerro`,
		party: `Revolutionary Union`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `8 December 1931`,
		leftOffice: `30 April 1933`,
	},
	{
		id: 22059,
		countryId,
		name: `Óscar R. Benavides`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `30 April 1933`,
		leftOffice: `8 December 1939`,
	},
	{
		id: 22060,
		countryId,
		name: `Manuel Prado`,
		party: `Pradist Democratic Movement`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `8 December 1939`,
		leftOffice: `28 July 1945`,
	},
	{
		id: 22061,
		countryId,
		name: `José Bustamante`,
		party: `National Democratic Front`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `28 July 1945`,
		leftOffice: `29 October 1948`,
	},
	{
		id: 22062,
		countryId,
		name: `Manuel A. Odría`,
		party: `Unión Nacional Odriista`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `27 October 1948`,
		leftOffice: `1 June 1950`,
	},
	{
		id: 22063,
		countryId,
		name: `Zenón Noriega Agüero`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 June 1950`,
		leftOffice: `28 July 1950`,
	},
	{
		id: 22064,
		countryId,
		name: `Manuel A. Odría`,
		party: `Unión Nacional Odriista`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `28 July 1950`,
		leftOffice: `28 July 1956`,
	},
	{
		id: 22065,
		countryId,
		name: `Manuel Prado`,
		party: `Pradist Democratic Movement`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `28 July 1956`,
		leftOffice: `18 July 1962`,
	},
	{
		id: 22066,
		countryId,
		name: `Ricardo Pérez Godoy`,
		party: `Peruvian Armed Forces - Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 July 1962`,
		leftOffice: `3 March 1963`,
	},
	{
		id: 22067,
		countryId,
		name: `Nicolás Lindley`,
		party: `Peruvian Armed Forces - Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 March 1963`,
		leftOffice: `28 July 1963`,
	},
	{
		id: 22068,
		countryId,
		name: `Fernando Belaúnde Terry`,
		party: `Popular Action`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `28 July 1963`,
		leftOffice: `3 October 1968`,
	},
	{
		id: 22069,
		countryId,
		name: `Juan Velasco Alvarado`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.LEFT,
		tookOffice: `3 October 1968`,
		leftOffice: `30 August 1975`,
	},
	{
		id: 22070,
		countryId,
		name: `Francisco Morales Bermúdez`,
		party: `Peruvian Armed Forces`,
		leaning: leanings.RIGHT,
		tookOffice: `30 August 1975`,
		leftOffice: `28 July 1980`,
	},
	{
		id: 22071,
		countryId,
		name: `Fernando Belaúnde Terry`,
		party: `Popular Action`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `28 July 1980`,
		leftOffice: `28 July 1985`,
	},
	{
		id: 22072,
		countryId,
		name: `Alan García`,
		party: `American Popular Revolutionary Alliance`,
		leaning: leanings.LEFT,
		tookOffice: `28 July 1985`,
		leftOffice: `28 July 1990`,
	},
	{
		id: 22073,
		countryId,
		name: `Alberto Fujimori`,
		party: `Peru 2000`,
		leaning: leanings.RIGHT,
		tookOffice: `28 July 1990`,
		leftOffice: `22 November 2000`,
	},
	{
		id: 22074,
		countryId,
		name: `Valentín Paniagua`,
		party: `Popular Action`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `22 November 2000`,
		leftOffice: `28 July 2001`,
	},
	{
		id: 22075,
		countryId,
		name: `Alejandro Toledo`,
		party: `Possible Peru`,
		leaning: leanings.CENTER_LEFT,
		tookOffice: `28 July 2001`,
		leftOffice: `28 July 2006`,
	},
	{
		id: 22076,
		countryId,
		name: `Alan García`,
		party: `American Popular Revolutionary Alliance`,
		leaning: leanings.CENTRIST,
		tookOffice: `28 July 2006`,
		leftOffice: `28 July 2011`,
	},
	{
		id: 22077,
		countryId,
		name: `Ollanta Humala`,
		party: `Peruvian Nationalist Party`,
		leaning: leanings.LEFT,
		tookOffice: `July 28, 2011`,
		leftOffice: `July 28, 2016`,
	},
	{
		id: 22078,
		countryId,
		name: `Pedro Pablo Kuczynski`,
		party: `Peruvians for Change`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `July 28 2016`,
		leftOffice: `March 23 2018`,
	},
	{
		id: 22079,
		countryId,
		name: `Martín Vizcarra`,
		party: `Peruvians for Change`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `23 March 2018`,
		leftOffice: `10 November 2020`,
	},
	{
		id: 22080,
		countryId,
		name: `Manuel Merino`,
		party: `Popular Action`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `10 November 2020`,
		leftOffice: `17 November 2020`,
	},
	{
		id: 22081,
		countryId,
		name: `Francisco Sagasti`,
		party: `Purple Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `17 November 2020`,
		leftOffice: `28 July 2021`,
	},
	{
		id: 22082,
		countryId,
		name: `Pedro Castillo`,
		party: `Free Peru`,
		leaning: leanings.FAR_LEFT,
		tookOffice: `28 July 2021`,
		leftOffice: `7 December 2022`,
	},
	{
		id: 22083,
		countryId,
		name: `Dina Boluarte`,
		party: `Independent`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `7 December 2022`,
		leftOffice: `10 October 2025`,
	},
	{
		id: 22084,
		countryId,
		name: `José Jerí`,
		party: `We Are Peru`,
		leaning: leanings.RIGHT,
		tookOffice: `10 October 2025`,
		leftOffice: null,
	}
];
