import type { LeaderSeed } from '../../src/data/types';
import { leanings } from '../../src/data/types';

export const source = `https://en.wikipedia.org/wiki/List_of_presidents_of_Uruguay`;

const countryId = 21;

export const uruguay: LeaderSeed[] = [
	{
		id: 25000,
		countryId,
		name: `Viceroyalty of the Río de la Plata`,
		party: `Kingdom of Spain`,
		leaning: leanings.MONARCHY,
		tookOffice: `1 August 1776`,
		leftOffice: `9 July 1814`,
	},
	{
		id: 25001,
		countryId,
		name: `Nicolás Rodríguez Peña - United Provinces of the Rio de la Plata`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `9 July 1814`,
		leftOffice: `25 August 1814`,
	},
	{
		id: 25002,
		countryId,
		name: `Miguel Estanislao Soler - United Provinces of the Rio de la Plata`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 August 1814`,
		leftOffice: `26 February 1815`,
	},
	{
		id: 25003,
		countryId,
		name: `Fernando Otorgués - United Provinces of the Rio de la Plata`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `26 February 1815`,
		leftOffice: `July 1815`,
	},
	{
		id: 25004,
		countryId,
		name: `Miguel Barreiro - United Provinces of the Rio de la Plata`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `July 1815`,
		leftOffice: `20 January 1817`,
	},
	{
		id: 25005,
		countryId,
		name: `Carlos Frederico Lecor - United Kingdom of Portugal, Brazil and the Algarves`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 January 1817`,
		leftOffice: `3 February 1826`,
	},
	{
		id: 25006,
		countryId,
		name: `Francisco de Paula Magessi Tavares de Carvalho - Empire of Brazil`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `3 February 1826`,
		leftOffice: `27 August 1828`,
	},
	{
		id: 25007,
		countryId,
		name: `Juan Antonio Lavalleja - United Provinces of the Rio de la Plata`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `19 September 1825`,
		leftOffice: `5 July 1826`,
	},
	{
		id: 25008,
		countryId,
		name: `Joaquín Suárez - United Provinces of the Rio de la Plata`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 July 1826`,
		leftOffice: `12 October 1827`,
	},
	{
		id: 25009,
		countryId,
		name: `Luis Eduardo Pérez - United Provinces of the Rio de la Plata`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 October 1827`,
		leftOffice: `27 August 1828`,
	},
	{
		id: 25010,
		countryId,
		name: `Luis Eduardo Pérez`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `27 August 1828`,
		leftOffice: `2 December 1828`,
	},
	{
		id: 25011,
		countryId,
		name: `Joaquín Suárez`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 December 1828`,
		leftOffice: `22 December 1828`,
	},
	{
		id: 25012,
		countryId,
		name: `José Rondeau`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `22 December 1828`,
		leftOffice: `17 April 1830`,
	},
	{
		id: 25013,
		countryId,
		name: `Juan Antonio Lavalleja`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `17 April 1830`,
		leftOffice: `28 June 1830`,
	},
	{
		id: 25014,
		countryId,
		name: `Juan Antonio Lavalleja`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `28 June 1830`,
		leftOffice: `24 October 1830`,
	},
	{
		id: 25015,
		countryId,
		name: `Luis Eduardo Pérez`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `24 October 1830`,
		leftOffice: `6 November 1830`,
	},
	{
		id: 25016,
		countryId,
		name: `Fructuoso Rivera`,
		party: `Independent`,
		leaning: leanings.CENTRIST,
		tookOffice: `6 November 1830`,
		leftOffice: `24 October 1834`,
	},
	{
		id: 25017,
		countryId,
		name: `Carlos Anaya`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `24 October 1834`,
		leftOffice: `1 March 1835`,
	},
	{
		id: 25018,
		countryId,
		name: `Manuel Oribe`,
		party: `National Party / White Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1835`,
		leftOffice: `24 October 1838`,
	},
	{
		id: 25019,
		countryId,
		name: `Gabriel Antonio Pereira`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `24 October 1838`,
		leftOffice: `1 March 1839`,
	},
	{
		id: 25020,
		countryId,
		name: `Fructuoso Rivera`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1839`,
		leftOffice: `1 March 1843`,
	},
	{
		id: 25021,
		countryId,
		name: `Manuel Oribe`,
		party: `National Party / White Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `16 February 1843`,
		leftOffice: `8 October 1851`,
	},
	{
		id: 25022,
		countryId,
		name: `Joaquín Suárez`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1843`,
		leftOffice: `15 February 1852`,
	},
	{
		id: 25023,
		countryId,
		name: `Bernardo Prudencio Berro`,
		party: `National Party / White Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 February 1852`,
		leftOffice: `1 March 1852`,
	},
	{
		id: 25024,
		countryId,
		name: `Juan Francisco Giró`,
		party: `National Party / White Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1852`,
		leftOffice: `25 September 1853`,
	},
	{
		id: 25025,
		countryId,
		name: `Triumvirate of Venancio Flores, Fructuoso Rivera, and Juan Antonio Lavalleja`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 September 1853`,
		leftOffice: `12 March 1854`,
	},
	{
		id: 25028,
		countryId,
		name: `Venancio Flores`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `12 March 1854`,
		leftOffice: `10 September 1855`,
	},
	{
		id: 25030,
		countryId,
		name: `Manuel Basilio Bustamante`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 September 1855`,
		leftOffice: `15 February 1856`,
	},
	{
		id: 25031,
		countryId,
		name: `José María Plá`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 February 1856`,
		leftOffice: `1 March 1856`,
	},
	{
		id: 25032,
		countryId,
		name: `Gabriel Antonio Pereira`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1856`,
		leftOffice: `1 March 1860`,
	},
	{
		id: 25033,
		countryId,
		name: `Bernardo Prudencio Berro`,
		party: `National Party / White Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1860`,
		leftOffice: `1 March 1864`,
	},
	{
		id: 25034,
		countryId,
		name: `Atanasio Cruz Aguirre`,
		party: `National Party / White Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1864`,
		leftOffice: `15 February 1865`,
	},
	{
		id: 25035,
		countryId,
		name: `Tomás Villalba`,
		party: `National Party / White Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `15 February 1865`,
		leftOffice: `20 February 1865`,
	},
	{
		id: 25036,
		countryId,
		name: `Venancio Flores`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `20 February 1865`,
		leftOffice: `15 February 1868`,
	},
	{
		id: 25037,
		countryId,
		name: `Pedro Varela`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 February 1868`,
		leftOffice: `1 March 1868`,
	},
	{
		id: 25038,
		countryId,
		name: `Lorenzo Batlle`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1868`,
		leftOffice: `1 March 1872`,
	},
	{
		id: 25039,
		countryId,
		name: `Tomás Gomensoro Albín`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1872`,
		leftOffice: `1 March 1873`,
	},
	{
		id: 25040,
		countryId,
		name: `José Eugenio Ellauri`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1873`,
		leftOffice: `22 January 1875`,
	},
	{
		id: 25041,
		countryId,
		name: `Pedro Varela`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `22 January 1875`,
		leftOffice: `10 March 1876`,
	},
	{
		id: 25042,
		countryId,
		name: `Lorenzo Latorre`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `10 March 1876`,
		leftOffice: `1 March 1879`,
	},
	{
		id: 25044,
		countryId,
		name: `Lorenzo Latorre`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1879`,
		leftOffice: `15 March 1880`,
	},
	{
		id: 25045,
		countryId,
		name: `Francisco Antonino Vidal`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `15 March 1880`,
		leftOffice: `1 March 1882`,
	},
	{
		id: 25046,
		countryId,
		name: `Máximo Santos`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1882`,
		leftOffice: `1 March 1886`,
	},
	{
		id: 25047,
		countryId,
		name: `Francisco Antonino Vidal`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1886`,
		leftOffice: `24 May 1886`,
	},
	{
		id: 25048,
		countryId,
		name: `Máximo Santos`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `24 May 1886`,
		leftOffice: `18 November 1886`,
	},
	{
		id: 25049,
		countryId,
		name: `Máximo Tajes`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `18 November 1886`,
		leftOffice: `1 March 1890`,
	},
	{
		id: 25050,
		countryId,
		name: `Julio Herrera y Obes`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1890`,
		leftOffice: `1 March 1894`,
	},
	{
		id: 25051,
		countryId,
		name: `Duncan Stewart`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1894`,
		leftOffice: `21 March 1894`,
	},
	{
		id: 25052,
		countryId,
		name: `Juan Idiarte Borda`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `21 March 1894`,
		leftOffice: `25 August 1897`,
	},
	{
		id: 25053,
		countryId,
		name: `Juan Lindolfo Cuestas`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `25 August 1897`,
		leftOffice: `5 February 1899`,
	},
	{
		id: 25054,
		countryId,
		name: `José Batlle y Ordoñez`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `5 February 1899`,
		leftOffice: `1 March 1899`,
	},
	{
		id: 25055,
		countryId,
		name: `Juan Lindolfo Cuestas`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1899`,
		leftOffice: `1 March 1903`,
	},
	{
		id: 25056,
		countryId,
		name: `José Batlle y Ordoñez`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1903`,
		leftOffice: `1 March 1907`,
	},
	{
		id: 25057,
		countryId,
		name: `Claudio Wílliman`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1907`,
		leftOffice: `1 March 1911`,
	},
	{
		id: 25058,
		countryId,
		name: `José Batlle y Ordoñez`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1911`,
		leftOffice: `1 March 1915`,
	},
	{
		id: 25059,
		countryId,
		name: `Feliciano Viera`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1915`,
		leftOffice: `1 March 1919`,
	},
	{
		id: 25060,
		countryId,
		name: `Baltasar Brum`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1919`,
		leftOffice: `1 March 1923`,
	},
	{
		id: 25061,
		countryId,
		name: `José Serrato`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1923`,
		leftOffice: `1 March 1927`,
	},
	{
		id: 25062,
		countryId,
		name: `Juan Campisteguy`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1927`,
		leftOffice: `1 March 1931`,
	},
	{
		id: 25063,
		countryId,
		name: `Gabriel Terra`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1931`,
		leftOffice: `19 June 1938`,
	},
	{
		id: 25064,
		countryId,
		name: `Alfredo Baldomir Ferrari`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `19 June 1938`,
		leftOffice: `1 March 1943`,
	},
	{
		id: 25065,
		countryId,
		name: `Juan José de Amézaga`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1943`,
		leftOffice: `1 March 1947`,
	},
	{
		id: 25066,
		countryId,
		name: `Tomás Berreta`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1947`,
		leftOffice: `2 August 1947`,
	},
	{
		id: 25067,
		countryId,
		name: `Luis Batlle Berres`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `2 August 1947`,
		leftOffice: `1 March 1951`,
	},
	{
		id: 25068,
		countryId,
		name: `Andres Martínez Trueba`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1951`,
		leftOffice: `1 March 1952`,
	},
	{
		id: 25069,
		countryId,
		name: `National Council of Government`,
		party: `National Council of Government`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1952`,
		leftOffice: `1 March 1967`,
	},
	{
		id: 25070,
		countryId,
		name: `Óscar Diego Gestido`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1967`,
		leftOffice: `6 December 1967`,
	},
	{
		id: 25071,
		countryId,
		name: `Jorge Pacheco`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `6 December 1967`,
		leftOffice: `1 March 1972`,
	},
	{
		id: 25072,
		countryId,
		name: `Juan María Bordaberry`,
		party: `Colorado Party / Civic-Military Dictatorship`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 March 1972`,
		leftOffice: `12 June 1976`,
	},
	{
		id: 25073,
		countryId,
		name: `Alberto Demicheli`,
		party: `Colorado Party / Civic-Military Dictatorship`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `12 June 1976`,
		leftOffice: `1 September 1976`,
	},
	{
		id: 25074,
		countryId,
		name: `Aparicio Méndez`,
		party: `National Party / White Party / Civic-Military Dictatorship`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 September 1976`,
		leftOffice: `1 September 1981`,
	},
	{
		id: 25075,
		countryId,
		name: `Gregorio Álvarez`,
		party: `Independent - Armed Forces of Uruguay`,
		leaning: leanings.FAR_RIGHT,
		tookOffice: `1 September 1981`,
		leftOffice: `12 February 1985`,
	},
	{
		id: 25076,
		countryId,
		name: `Rafael Addiego`,
		party: `Civic Union Party`,
		leaning: leanings.RIGHT,
		tookOffice: `12 February 1985`,
		leftOffice: `1 March 1985`,
	},
	{
		id: 25077,
		countryId,
		name: `Julio María Sanguinetti`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1985`,
		leftOffice: `1 March 1990`,
	},
	{
		id: 25078,
		countryId,
		name: `Luis Alberto Lacalle`,
		party: `National Party / White Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 1990`,
		leftOffice: `1 March 1995`,
	},
	{
		id: 25079,
		countryId,
		name: `Julio María Sanguinetti`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 1995`,
		leftOffice: `1 March 2000`,
	},
	{
		id: 25080,
		countryId,
		name: `Jorge Batlle`,
		party: `Colorado Party`,
		leaning: leanings.CENTRIST,
		tookOffice: `1 March 2000`,
		leftOffice: `1 March 2005`,
	},
	{
		id: 25081,
		countryId,
		name: `Tabaré Vázquez`,
		party: `Broad Front`,
		leaning: leanings.LEFT,
		tookOffice: `1 March 2005`,
		leftOffice: `1 March 2010`,
	},
	{
		id: 25082,
		countryId,
		name: `José Mujica`,
		party: `Broad Front`,
		leaning: leanings.LEFT,
		tookOffice: `1 March 2010`,
		leftOffice: `1 March 2015`,
	},
	{
		id: 25083,
		countryId,
		name: `Tabaré Vázquez`,
		party: `Broad Front`,
		leaning: leanings.LEFT,
		tookOffice: `1 March 2015`,
		leftOffice: `1 March 2020`,
	},
	{
		id: 25084,
		countryId,
		name: `Luis Lacalle Pou`,
		party: `National Party / White Party`,
		leaning: leanings.CENTER_RIGHT,
		tookOffice: `1 March 2020`,
		leftOffice: `1 March 2025`,
	},
	{
		id: 25085,
		countryId,
		name: `Yamandú Orsi`,
		party: `Broad Front`,
		leaning: leanings.LEFT,
		tookOffice: `1 March 2025`,
		leftOffice: null,
	}
];
